module Amocrm
  module Models
    module V4
      module Leads
        type unsorted_accept_response =
          Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse
          | Amocrm::Models::V4::Leads::UnsortedAcceptResponse::Problem

        module UnsortedAcceptResponse
          extend Amocrm::Internal::Type::Union

          type unsorted_accept_response =
            {
              _embedded: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded,
              category: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category,
              created_at: Integer,
              pipeline_id: Integer,
              uid: String
            }

          class UnsortedAcceptResponse < Amocrm::Internal::Type::BaseModel
            attr_reader _embedded: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded?

            def _embedded=: (
              Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded
            ) -> Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded

            attr_reader category: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category?

            def category=: (
              Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category
            ) -> Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category

            attr_reader created_at: Integer?

            def created_at=: (Integer) -> Integer

            attr_reader pipeline_id: Integer?

            def pipeline_id=: (Integer) -> Integer

            attr_reader uid: String?

            def uid=: (String) -> String

            def initialize: (
              ?_embedded: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded,
              ?category: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category,
              ?created_at: Integer,
              ?pipeline_id: Integer,
              ?uid: String
            ) -> void

            def to_hash: -> {
              _embedded: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded,
              category: Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category,
              created_at: Integer,
              pipeline_id: Integer,
              uid: String
            }

            type embedded =
              {
                companies: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company],
                contacts: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact],
                leads: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]
              }

            class Embedded < Amocrm::Internal::Type::BaseModel
              attr_reader companies: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company]?

              def companies=: (
                ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company]
              ) -> ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company]

              attr_reader contacts: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact]?

              def contacts=: (
                ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact]
              ) -> ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact]

              attr_reader leads: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]?

              def leads=: (
                ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]
              ) -> ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]

              def initialize: (
                ?companies: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company],
                ?contacts: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact],
                ?leads: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]
              ) -> void

              def to_hash: -> {
                companies: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Company],
                contacts: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Contact],
                leads: ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::Embedded::Lead]
              }

              type company = { id: Integer, _links: top }

              class Company < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type contact = { id: Integer, _links: top }

              class Contact < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type lead = { id: Integer, _links: top }

              class Lead < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end
            end

            type category = :sip | :mail | :chats | :forms

            module Category
              extend Amocrm::Internal::Type::Enum

              SIP: :sip
              MAIL: :mail
              CHATS: :chats
              FORMS: :forms

              def self?.values: -> ::Array[Amocrm::Models::V4::Leads::UnsortedAcceptResponse::UnsortedAcceptResponse::category]
            end
          end

          type problem =
            { detail: String, status: Integer, title: String, type: String }

          class Problem < Amocrm::Internal::Type::BaseModel
            attr_reader detail: String?

            def detail=: (String) -> String

            attr_reader status: Integer?

            def status=: (Integer) -> Integer

            attr_reader title: String?

            def title=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?detail: String,
              ?status: Integer,
              ?title: String,
              ?type: String
            ) -> void

            def to_hash: -> {
              detail: String,
              status: Integer,
              title: String,
              type: String
            }
          end

          def self?.variants: -> ::Array[Amocrm::Models::V4::Leads::unsorted_accept_response]
        end
      end
    end
  end
end
