module Amocrm
  module Models
    type api_custom_field_groups_create_response =
      Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse
      | Amocrm::Models::APICustomFieldGroupsCreateResponse::Problem

    module APICustomFieldGroupsCreateResponse
      extend Amocrm::Internal::Type::Union

      type custom_field_group_create_response =
        {
          _embedded: Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded,
          _links: top
        }

      class CustomFieldGroupCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded
        ) -> Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            groups: ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader groups: ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]?

          def groups=: (
            ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]
          ) -> ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]

          def initialize: (
            ?groups: ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]
          ) -> void

          def to_hash: -> {
            groups: ::Array[Amocrm::Models::APICustomFieldGroupsCreateResponse::CustomFieldGroupCreateResponse::Embedded::Group]
          }

          type group = { id: Integer, name: String, request_id: String }

          class Group < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader request_id: String?

            def request_id=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?name: String,
              ?request_id: String
            ) -> void

            def to_hash: -> { id: Integer, name: String, request_id: String }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_custom_field_groups_create_response]
    end
  end
end
