module Amocrm
  module Models
    type api_custom_fields_get_by_id_params =
      { entity_type: String } & Amocrm::Internal::Type::request_parameters

    class APICustomFieldsGetByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor entity_type: String

      def initialize: (
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        entity_type: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
