module Amocrm
  module Models
    type api_catalogs_update_response =
      Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse
      | Amocrm::Models::APICatalogsUpdateResponse::Problem

    module APICatalogsUpdateResponse
      extend Amocrm::Internal::Type::Union

      type catalog_update_response =
        {
          _embedded: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded,
          _links: top
        }

      class CatalogUpdateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded
        ) -> Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            catalogs: ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader catalogs: ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]?

          def catalogs=: (
            ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]
          ) -> ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]

          def initialize: (
            ?catalogs: ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]
          ) -> void

          def to_hash: -> {
            catalogs: ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog]
          }

          type catalog =
            {
              id: Integer,
              _links: top,
              account_id: Integer,
              can_add_elements: bool,
              can_be_deleted: bool,
              can_link_multiple: bool,
              can_show_in_cards: bool,
              created_at: Integer,
              created_by: Integer,
              name: String,
              request_id: String,
              sdk_widget_code: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::sdk_widget_code?,
              sort: Integer,
              type: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_,
              updated_at: Integer,
              updated_by: Integer
            }

          class Catalog < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader account_id: Integer?

            def account_id=: (Integer) -> Integer

            attr_reader can_add_elements: bool?

            def can_add_elements=: (bool) -> bool

            attr_reader can_be_deleted: bool?

            def can_be_deleted=: (bool) -> bool

            attr_reader can_link_multiple: bool?

            def can_link_multiple=: (bool) -> bool

            attr_reader can_show_in_cards: bool?

            def can_show_in_cards=: (bool) -> bool

            attr_reader created_at: Integer?

            def created_at=: (Integer) -> Integer

            attr_reader created_by: Integer?

            def created_by=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader request_id: String?

            def request_id=: (String) -> String

            attr_accessor sdk_widget_code: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::sdk_widget_code?

            attr_reader sort: Integer?

            def sort=: (Integer) -> Integer

            attr_reader type: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_?

            def type=: (
              Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_
            ) -> Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            attr_reader updated_by: Integer?

            def updated_by=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?account_id: Integer,
              ?can_add_elements: bool,
              ?can_be_deleted: bool,
              ?can_link_multiple: bool,
              ?can_show_in_cards: bool,
              ?created_at: Integer,
              ?created_by: Integer,
              ?name: String,
              ?request_id: String,
              ?sdk_widget_code: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::sdk_widget_code?,
              ?sort: Integer,
              ?type: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_,
              ?updated_at: Integer,
              ?updated_by: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              _links: top,
              account_id: Integer,
              can_add_elements: bool,
              can_be_deleted: bool,
              can_link_multiple: bool,
              can_show_in_cards: bool,
              created_at: Integer,
              created_by: Integer,
              name: String,
              request_id: String,
              sdk_widget_code: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::sdk_widget_code?,
              sort: Integer,
              type: Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_,
              updated_at: Integer,
              updated_by: Integer
            }

            type sdk_widget_code = String | Integer

            module SDKWidgetCode
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::sdk_widget_code]
            end

            type type_ = :regular | :invoices | :products | String

            module Type
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::APICatalogsUpdateResponse::CatalogUpdateResponse::Embedded::Catalog::type_]

              REGULAR: :regular
              INVOICES: :invoices
              PRODUCTS: :products
            end
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_catalogs_update_response]
    end
  end
end
