module Amocrm
  module Models
    type api_tasks_create_params =
      { body: ::Array[Amocrm::APITasksCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APITasksCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APITasksCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APITasksCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APITasksCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          text: String,
          complete_till: Integer,
          created_by: Integer,
          entity_id: Integer,
          entity_type: String,
          request_id: String,
          responsible_user_id: Integer,
          task_type_id: Integer,
          updated_by: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor text: String

        attr_reader complete_till: Integer?

        def complete_till=: (Integer) -> Integer

        attr_reader created_by: Integer?

        def created_by=: (Integer) -> Integer

        attr_reader entity_id: Integer?

        def entity_id=: (Integer) -> Integer

        attr_reader entity_type: String?

        def entity_type=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader responsible_user_id: Integer?

        def responsible_user_id=: (Integer) -> Integer

        attr_reader task_type_id: Integer?

        def task_type_id=: (Integer) -> Integer

        attr_reader updated_by: Integer?

        def updated_by=: (Integer) -> Integer

        def initialize: (
          text: String,
          ?complete_till: Integer,
          ?created_by: Integer,
          ?entity_id: Integer,
          ?entity_type: String,
          ?request_id: String,
          ?responsible_user_id: Integer,
          ?task_type_id: Integer,
          ?updated_by: Integer
        ) -> void

        def to_hash: -> {
          text: String,
          complete_till: Integer,
          created_by: Integer,
          entity_id: Integer,
          entity_type: String,
          request_id: String,
          responsible_user_id: Integer,
          task_type_id: Integer,
          updated_by: Integer
        }
      end
    end
  end
end
