module Amocrm
  module Models
    type api_pipelines_create_params =
      { body: ::Array[Amocrm::APIPipelinesCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APIPipelinesCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APIPipelinesCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APIPipelinesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APIPipelinesCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          name: String,
          _embedded: Amocrm::APIPipelinesCreateParams::Body::Embedded,
          is_main: bool,
          is_unsorted_on: bool,
          request_id: String,
          sort: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader _embedded: Amocrm::APIPipelinesCreateParams::Body::Embedded?

        def _embedded=: (
          Amocrm::APIPipelinesCreateParams::Body::Embedded
        ) -> Amocrm::APIPipelinesCreateParams::Body::Embedded

        attr_reader is_main: bool?

        def is_main=: (bool) -> bool

        attr_reader is_unsorted_on: bool?

        def is_unsorted_on=: (bool) -> bool

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        def initialize: (
          name: String,
          ?_embedded: Amocrm::APIPipelinesCreateParams::Body::Embedded,
          ?is_main: bool,
          ?is_unsorted_on: bool,
          ?request_id: String,
          ?sort: Integer
        ) -> void

        def to_hash: -> {
          name: String,
          _embedded: Amocrm::APIPipelinesCreateParams::Body::Embedded,
          is_main: bool,
          is_unsorted_on: bool,
          request_id: String,
          sort: Integer
        }

        type embedded =
          {
            statuses: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader statuses: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]?

          def statuses=: (
            ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]
          ) -> ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]

          def initialize: (
            ?statuses: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]
          ) -> void

          def to_hash: -> {
            statuses: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status]
          }

          type status =
            {
              name: String,
              color: String,
              descriptions: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description],
              request_id: String,
              sort: Integer
            }

          class Status < Amocrm::Internal::Type::BaseModel
            attr_accessor name: String

            attr_reader color: String?

            def color=: (String) -> String

            attr_reader descriptions: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description]?

            def descriptions=: (
              ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description]
            ) -> ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description]

            attr_reader request_id: String?

            def request_id=: (String) -> String

            attr_reader sort: Integer?

            def sort=: (Integer) -> Integer

            def initialize: (
              name: String,
              ?color: String,
              ?descriptions: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description],
              ?request_id: String,
              ?sort: Integer
            ) -> void

            def to_hash: -> {
              name: String,
              color: String,
              descriptions: ::Array[Amocrm::APIPipelinesCreateParams::Body::Embedded::Status::Description],
              request_id: String,
              sort: Integer
            }

            type description =
              { id: Integer, description: String, level: String }

            class Description < Amocrm::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader description: String?

              def description=: (String) -> String

              attr_reader level: String?

              def level=: (String) -> String

              def initialize: (
                ?id: Integer,
                ?description: String,
                ?level: String
              ) -> void

              def to_hash: -> {
                id: Integer,
                description: String,
                level: String
              }
            end
          end
        end
      end
    end
  end
end
