module Amocrm
  module Models
    type api_catalog_elements_update_by_id_params =
      {
        catalog_id: Integer,
        custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue],
        name: String,
        request_id: String
      }
      & Amocrm::Internal::Type::request_parameters

    class APICatalogElementsUpdateByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor catalog_id: Integer

      attr_reader custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue]?

      def custom_fields_values=: (
        ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue]
      ) -> ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue]

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader request_id: String?

      def request_id=: (String) -> String

      def initialize: (
        catalog_id: Integer,
        ?custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_id: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        catalog_id: Integer,
        custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue],
        name: String,
        request_id: String,
        request_options: Amocrm::RequestOptions
      }

      type custom_fields_value =
        {
          values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue::Value],
          field_code: String,
          field_id: Integer,
          field_name: String,
          field_type: String
        }

      class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
        attr_accessor values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue::Value]

        attr_reader field_code: String?

        def field_code=: (String) -> String

        attr_reader field_id: Integer?

        def field_id=: (Integer) -> Integer

        attr_reader field_name: String?

        def field_name=: (String) -> String

        attr_reader field_type: String?

        def field_type=: (String) -> String

        def initialize: (
          values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue::Value],
          ?field_code: String,
          ?field_id: Integer,
          ?field_name: String,
          ?field_type: String
        ) -> void

        def to_hash: -> {
          values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue::Value],
          field_code: String,
          field_id: Integer,
          field_name: String,
          field_type: String
        }

        type value = { value: top, enum_code: String, enum_id: Integer }

        class Value < Amocrm::Internal::Type::BaseModel
          attr_accessor value: top

          attr_reader enum_code: String?

          def enum_code=: (String) -> String

          attr_reader enum_id: Integer?

          def enum_id=: (Integer) -> Integer

          def initialize: (
            value: top,
            ?enum_code: String,
            ?enum_id: Integer
          ) -> void

          def to_hash: -> { value: top, enum_code: String, enum_id: Integer }
        end
      end
    end
  end
end
