module Amocrm
  module Models
    type api_website_buttons_create_response =
      Amocrm::Models::APIWebsiteButtonsCreateResponse::WebsiteButtonCreateResponse
      | Amocrm::Models::APIWebsiteButtonsCreateResponse::Problem

    module APIWebsiteButtonsCreateResponse
      extend Amocrm::Internal::Type::Union

      type website_button_create_response =
        { source_id: Integer, trusted_websites: ::Array[String] }

      class WebsiteButtonCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader source_id: Integer?

        def source_id=: (Integer) -> Integer

        attr_reader trusted_websites: ::Array[String]?

        def trusted_websites=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?source_id: Integer,
          ?trusted_websites: ::Array[String]
        ) -> void

        def to_hash: -> {
          source_id: Integer,
          trusted_websites: ::Array[String]
        }
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_website_buttons_create_response]
    end
  end
end
