module Amocrm
  module Models
    type api_customer_statuses_create_params =
      { body: ::Array[Amocrm::APICustomerStatusesCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APICustomerStatusesCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APICustomerStatusesCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APICustomerStatusesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APICustomerStatusesCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        { name: String, color: String, request_id: String, sort: Integer }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader color: String?

        def color=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        def initialize: (
          name: String,
          ?color: String,
          ?request_id: String,
          ?sort: Integer
        ) -> void

        def to_hash: -> {
          name: String,
          color: String,
          request_id: String,
          sort: Integer
        }
      end
    end
  end
end
