module Amocrm
  module Models
    type api_tasks_update_by_id_params =
      {
        complete_till: Integer,
        entity_id: Integer,
        entity_type: String,
        is_completed: bool,
        responsible_user_id: Integer,
        result: Amocrm::APITasksUpdateByIDParams::Result,
        task_type_id: Integer,
        text: String
      }
      & Amocrm::Internal::Type::request_parameters

    class APITasksUpdateByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader complete_till: Integer?

      def complete_till=: (Integer) -> Integer

      attr_reader entity_id: Integer?

      def entity_id=: (Integer) -> Integer

      attr_reader entity_type: String?

      def entity_type=: (String) -> String

      attr_reader is_completed: bool?

      def is_completed=: (bool) -> bool

      attr_reader responsible_user_id: Integer?

      def responsible_user_id=: (Integer) -> Integer

      attr_reader result: Amocrm::APITasksUpdateByIDParams::Result?

      def result=: (
        Amocrm::APITasksUpdateByIDParams::Result
      ) -> Amocrm::APITasksUpdateByIDParams::Result

      attr_reader task_type_id: Integer?

      def task_type_id=: (Integer) -> Integer

      attr_reader text: String?

      def text=: (String) -> String

      def initialize: (
        ?complete_till: Integer,
        ?entity_id: Integer,
        ?entity_type: String,
        ?is_completed: bool,
        ?responsible_user_id: Integer,
        ?result: Amocrm::APITasksUpdateByIDParams::Result,
        ?task_type_id: Integer,
        ?text: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        complete_till: Integer,
        entity_id: Integer,
        entity_type: String,
        is_completed: bool,
        responsible_user_id: Integer,
        result: Amocrm::APITasksUpdateByIDParams::Result,
        task_type_id: Integer,
        text: String,
        request_options: Amocrm::RequestOptions
      }

      type result = { text: String }

      class Result < Amocrm::Internal::Type::BaseModel
        attr_reader text: String?

        def text=: (String) -> String

        def initialize: (?text: String) -> void

        def to_hash: -> { text: String }
      end
    end
  end
end
