module Amocrm
  module Models
    type api_customer_segments_create_params =
      { body: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APICustomerSegmentsCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          name: String,
          color: String,
          custom_fields_values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue],
          request_id: String
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader color: String?

        def color=: (String) -> String

        attr_reader custom_fields_values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue]?

        def custom_fields_values=: (
          ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue]
        ) -> ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue]

        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (
          name: String,
          ?color: String,
          ?custom_fields_values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue],
          ?request_id: String
        ) -> void

        def to_hash: -> {
          name: String,
          color: String,
          custom_fields_values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue],
          request_id: String
        }

        type custom_fields_value =
          {
            values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer
          }

        class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
          attr_accessor values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value]

          attr_reader field_code: String?

          def field_code=: (String) -> String

          attr_reader field_id: Integer?

          def field_id=: (Integer) -> Integer

          def initialize: (
            values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value],
            ?field_code: String,
            ?field_id: Integer
          ) -> void

          def to_hash: -> {
            values: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer
          }

          type value =
            {
              value: Amocrm::Models::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value::value,
              enum_code: String,
              enum_id: Integer
            }

          class Value < Amocrm::Internal::Type::BaseModel
            attr_accessor value: Amocrm::Models::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value::value

            attr_reader enum_code: String?

            def enum_code=: (String) -> String

            attr_reader enum_id: Integer?

            def enum_id=: (Integer) -> Integer

            def initialize: (
              value: Amocrm::Models::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value::value,
              ?enum_code: String,
              ?enum_id: Integer
            ) -> void

            def to_hash: -> {
              value: Amocrm::Models::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value::value,
              enum_code: String,
              enum_id: Integer
            }

            type value = String | Integer | bool

            module Value
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::APICustomerSegmentsCreateParams::Body::CustomFieldsValue::Value::value]
            end
          end
        end
      end
    end
  end
end
