module Amocrm
  module Models
    type api_custom_fields_create_params =
      { body: ::Array[Amocrm::APICustomFieldsCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APICustomFieldsCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APICustomFieldsCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APICustomFieldsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APICustomFieldsCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          name: String,
          type: String,
          code: String,
          enums: ::Array[top],
          group_id: Integer,
          is_deletable: bool,
          is_multiple: bool,
          is_required: bool,
          is_visible: bool,
          request_id: String,
          settings: top,
          sort: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: String

        attr_reader code: String?

        def code=: (String) -> String

        attr_reader enums: ::Array[top]?

        def enums=: (::Array[top]) -> ::Array[top]

        attr_reader group_id: Integer?

        def group_id=: (Integer) -> Integer

        attr_reader is_deletable: bool?

        def is_deletable=: (bool) -> bool

        attr_reader is_multiple: bool?

        def is_multiple=: (bool) -> bool

        attr_reader is_required: bool?

        def is_required=: (bool) -> bool

        attr_reader is_visible: bool?

        def is_visible=: (bool) -> bool

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader settings: top?

        def settings=: (top) -> top

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        def initialize: (
          name: String,
          type: String,
          ?code: String,
          ?enums: ::Array[top],
          ?group_id: Integer,
          ?is_deletable: bool,
          ?is_multiple: bool,
          ?is_required: bool,
          ?is_visible: bool,
          ?request_id: String,
          ?settings: top,
          ?sort: Integer
        ) -> void

        def to_hash: -> {
          name: String,
          type: String,
          code: String,
          enums: ::Array[top],
          group_id: Integer,
          is_deletable: bool,
          is_multiple: bool,
          is_required: bool,
          is_visible: bool,
          request_id: String,
          settings: top,
          sort: Integer
        }
      end
    end
  end
end
