module Amocrm
  module Models
    type api_customer_bonus_points_change_response =
      Amocrm::Models::APICustomerBonusPointsChangeResponse::CustomerBonusPointsResponse
      | Amocrm::Models::APICustomerBonusPointsChangeResponse::Problem

    module APICustomerBonusPointsChangeResponse
      extend Amocrm::Internal::Type::Union

      type customer_bonus_points_response = { bonus_points: Integer }

      class CustomerBonusPointsResponse < Amocrm::Internal::Type::BaseModel
        attr_reader bonus_points: Integer?

        def bonus_points=: (Integer) -> Integer

        def initialize: (?bonus_points: Integer) -> void

        def to_hash: -> { bonus_points: Integer }
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_customer_bonus_points_change_response]
    end
  end
end
