module Amocrm
  module Models
    type api_account_get_response =
      Amocrm::Models::APIAccountGetResponse::AccountInfo
      | Amocrm::Models::APIAccountGetResponse::Problem

    module APIAccountGetResponse
      extend Amocrm::Internal::Type::Union

      type account_info =
        {
          id: Integer,
          _embedded: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded,
          _links: top,
          amojo_id: String,
          contact_name_display_order: Integer,
          country: String,
          created_at: Integer,
          created_by: Integer,
          currency: String,
          currency_symbol: String,
          current_user_id: Integer,
          customers_mode: Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode,
          drive_url: String,
          invoices_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings,
          is_api_filter_enabled: bool,
          is_helpbot_enabled: bool,
          is_loss_reason_enabled: bool,
          is_technical_account: bool,
          is_unsorted_on: bool,
          mobile_feature_version: Integer,
          name: String,
          subdomain: String,
          updated_at: Integer,
          updated_by: Integer,
          uuid: String,
          version: Integer
        }

      class AccountInfo < Amocrm::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader _embedded: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded?

        def _embedded=: (
          Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded
        ) -> Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        attr_reader amojo_id: String?

        def amojo_id=: (String) -> String

        attr_reader contact_name_display_order: Integer?

        def contact_name_display_order=: (Integer) -> Integer

        attr_reader country: String?

        def country=: (String) -> String

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader created_by: Integer?

        def created_by=: (Integer) -> Integer

        attr_reader currency: String?

        def currency=: (String) -> String

        attr_reader currency_symbol: String?

        def currency_symbol=: (String) -> String

        attr_reader current_user_id: Integer?

        def current_user_id=: (Integer) -> Integer

        attr_reader customers_mode: Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode?

        def customers_mode=: (
          Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode
        ) -> Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode

        attr_reader drive_url: String?

        def drive_url=: (String) -> String

        attr_reader invoices_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings?

        def invoices_settings=: (
          Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings
        ) -> Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings

        attr_reader is_api_filter_enabled: bool?

        def is_api_filter_enabled=: (bool) -> bool

        attr_reader is_helpbot_enabled: bool?

        def is_helpbot_enabled=: (bool) -> bool

        attr_reader is_loss_reason_enabled: bool?

        def is_loss_reason_enabled=: (bool) -> bool

        attr_reader is_technical_account: bool?

        def is_technical_account=: (bool) -> bool

        attr_reader is_unsorted_on: bool?

        def is_unsorted_on=: (bool) -> bool

        attr_reader mobile_feature_version: Integer?

        def mobile_feature_version=: (Integer) -> Integer

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader subdomain: String?

        def subdomain=: (String) -> String

        attr_reader updated_at: Integer?

        def updated_at=: (Integer) -> Integer

        attr_reader updated_by: Integer?

        def updated_by=: (Integer) -> Integer

        attr_reader uuid: String?

        def uuid=: (String) -> String

        attr_reader version: Integer?

        def version=: (Integer) -> Integer

        def initialize: (
          ?id: Integer,
          ?_embedded: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded,
          ?_links: top,
          ?amojo_id: String,
          ?contact_name_display_order: Integer,
          ?country: String,
          ?created_at: Integer,
          ?created_by: Integer,
          ?currency: String,
          ?currency_symbol: String,
          ?current_user_id: Integer,
          ?customers_mode: Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode,
          ?drive_url: String,
          ?invoices_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings,
          ?is_api_filter_enabled: bool,
          ?is_helpbot_enabled: bool,
          ?is_loss_reason_enabled: bool,
          ?is_technical_account: bool,
          ?is_unsorted_on: bool,
          ?mobile_feature_version: Integer,
          ?name: String,
          ?subdomain: String,
          ?updated_at: Integer,
          ?updated_by: Integer,
          ?uuid: String,
          ?version: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          _embedded: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded,
          _links: top,
          amojo_id: String,
          contact_name_display_order: Integer,
          country: String,
          created_at: Integer,
          created_by: Integer,
          currency: String,
          currency_symbol: String,
          current_user_id: Integer,
          customers_mode: Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode,
          drive_url: String,
          invoices_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::InvoicesSettings,
          is_api_filter_enabled: bool,
          is_helpbot_enabled: bool,
          is_loss_reason_enabled: bool,
          is_technical_account: bool,
          is_unsorted_on: bool,
          mobile_feature_version: Integer,
          name: String,
          subdomain: String,
          updated_at: Integer,
          updated_by: Integer,
          uuid: String,
          version: Integer
        }

        type embedded =
          {
            amojo_rights: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights,
            datetime_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings,
            task_types: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType],
            users_groups: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader amojo_rights: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights?

          def amojo_rights=: (
            Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights
          ) -> Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights

          attr_reader datetime_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings?

          def datetime_settings=: (
            Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings
          ) -> Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings

          attr_reader task_types: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType]?

          def task_types=: (
            ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType]
          ) -> ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType]

          attr_reader users_groups: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]?

          def users_groups=: (
            ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]
          ) -> ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]

          def initialize: (
            ?amojo_rights: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights,
            ?datetime_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings,
            ?task_types: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType],
            ?users_groups: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]
          ) -> void

          def to_hash: -> {
            amojo_rights: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::AmojoRights,
            datetime_settings: Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::DatetimeSettings,
            task_types: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::TaskType],
            users_groups: ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::Embedded::UsersGroup]
          }

          type amojo_rights = { can_create_groups: bool, can_direct: bool }

          class AmojoRights < Amocrm::Internal::Type::BaseModel
            attr_reader can_create_groups: bool?

            def can_create_groups=: (bool) -> bool

            attr_reader can_direct: bool?

            def can_direct=: (bool) -> bool

            def initialize: (
              ?can_create_groups: bool,
              ?can_direct: bool
            ) -> void

            def to_hash: -> { can_create_groups: bool, can_direct: bool }
          end

          type datetime_settings =
            {
              date_format: String,
              date_pattern: String,
              short_date_pattern: String,
              short_time_pattern: String,
              time_format: String,
              timezone: String,
              timezone_offset: String
            }

          class DatetimeSettings < Amocrm::Internal::Type::BaseModel
            attr_reader date_format: String?

            def date_format=: (String) -> String

            attr_reader date_pattern: String?

            def date_pattern=: (String) -> String

            attr_reader short_date_pattern: String?

            def short_date_pattern=: (String) -> String

            attr_reader short_time_pattern: String?

            def short_time_pattern=: (String) -> String

            attr_reader time_format: String?

            def time_format=: (String) -> String

            attr_reader timezone: String?

            def timezone=: (String) -> String

            attr_reader timezone_offset: String?

            def timezone_offset=: (String) -> String

            def initialize: (
              ?date_format: String,
              ?date_pattern: String,
              ?short_date_pattern: String,
              ?short_time_pattern: String,
              ?time_format: String,
              ?timezone: String,
              ?timezone_offset: String
            ) -> void

            def to_hash: -> {
              date_format: String,
              date_pattern: String,
              short_date_pattern: String,
              short_time_pattern: String,
              time_format: String,
              timezone: String,
              timezone_offset: String
            }
          end

          type task_type =
            {
              id: Integer,
              code: String,
              color: String,
              icon_id: Integer,
              name: String
            }

          class TaskType < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader code: String?

            def code=: (String) -> String

            attr_reader color: String?

            def color=: (String) -> String

            attr_reader icon_id: Integer?

            def icon_id=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?code: String,
              ?color: String,
              ?icon_id: Integer,
              ?name: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              code: String,
              color: String,
              icon_id: Integer,
              name: String
            }
          end

          type users_group = { id: Integer, name: String, uuid: String }

          class UsersGroup < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader uuid: String?

            def uuid=: (String) -> String

            def initialize: (?id: Integer, ?name: String, ?uuid: String) -> void

            def to_hash: -> { id: Integer, name: String, uuid: String }
          end
        end

        type customers_mode =
          :periodicity
          | :dynamic
          | :segments
          | :disabled
          | :unavailable
          | String

        module CustomersMode
          extend Amocrm::Internal::Type::Union

          def self?.variants: -> ::Array[Amocrm::Models::APIAccountGetResponse::AccountInfo::customers_mode]

          PERIODICITY: :periodicity
          DYNAMIC: :dynamic
          SEGMENTS: :segments
          DISABLED: :disabled
          UNAVAILABLE: :unavailable
        end

        type invoices_settings = { invoices_catalog_id: Integer, lang: String }

        class InvoicesSettings < Amocrm::Internal::Type::BaseModel
          attr_reader invoices_catalog_id: Integer?

          def invoices_catalog_id=: (Integer) -> Integer

          attr_reader lang: String?

          def lang=: (String) -> String

          def initialize: (?invoices_catalog_id: Integer, ?lang: String) -> void

          def to_hash: -> { invoices_catalog_id: Integer, lang: String }
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_account_get_response]
    end
  end
end
