module Amocrm
  module Models
    type api_contacts_create_response =
      Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse
      | Amocrm::Models::APIContactsCreateResponse::Problem

    module APIContactsCreateResponse
      extend Amocrm::Internal::Type::Union

      type contact_create_response =
        {
          _embedded: Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded,
          _links: top
        }

      class ContactCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded
        ) -> Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            contacts: ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader contacts: ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]?

          def contacts=: (
            ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]
          ) -> ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]

          def initialize: (
            ?contacts: ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]
          ) -> void

          def to_hash: -> {
            contacts: ::Array[Amocrm::Models::APIContactsCreateResponse::ContactCreateResponse::Embedded::Contact]
          }

          type contact = { id: Integer, _links: top, request_id: String }

          class Contact < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader request_id: String?

            def request_id=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?request_id: String
            ) -> void

            def to_hash: -> { id: Integer, _links: top, request_id: String }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_contacts_create_response]
    end
  end
end
