module Amocrm
  module Models
    type api_custom_field_groups_get_by_id_response =
      Amocrm::Models::APICustomFieldGroupsGetByIDResponse::CustomFieldGroup
      | Amocrm::Models::APICustomFieldGroupsGetByIDResponse::Problem

    module APICustomFieldGroupsGetByIDResponse
      extend Amocrm::Internal::Type::Union

      type custom_field_group =
        { id: Integer, is_predefined: bool, name: String, sort: Integer }

      class CustomFieldGroup < Amocrm::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader is_predefined: bool?

        def is_predefined=: (bool) -> bool

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        def initialize: (
          ?id: Integer,
          ?is_predefined: bool,
          ?name: String,
          ?sort: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          is_predefined: bool,
          name: String,
          sort: Integer
        }
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_custom_field_groups_get_by_id_response]
    end
  end
end
