module Amocrm
  module Models
    type api_pipelines_update_response =
      Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse
      | Amocrm::Models::APIPipelinesUpdateResponse::Problem

    module APIPipelinesUpdateResponse
      extend Amocrm::Internal::Type::Union

      type pipeline_update_response =
        {
          _embedded: Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded,
          _links: top
        }

      class PipelineUpdateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded
        ) -> Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            pipelines: ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader pipelines: ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]?

          def pipelines=: (
            ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]
          ) -> ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]

          def initialize: (
            ?pipelines: ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]
          ) -> void

          def to_hash: -> {
            pipelines: ::Array[Amocrm::Models::APIPipelinesUpdateResponse::PipelineUpdateResponse::Embedded::Pipeline]
          }

          type pipeline =
            {
              id: Integer,
              _links: top,
              request_id: String,
              updated_at: Integer
            }

          class Pipeline < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader request_id: String?

            def request_id=: (String) -> String

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?request_id: String,
              ?updated_at: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              _links: top,
              request_id: String,
              updated_at: Integer
            }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::api_pipelines_update_response]
    end
  end
end
