module Amocrm
  module Models
    type api_catalog_elements_update_params =
      { body: ::Array[Amocrm::APICatalogElementsUpdateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class APICatalogElementsUpdateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::APICatalogElementsUpdateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::APICatalogElementsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::APICatalogElementsUpdateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          id: Integer,
          custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue],
          name: String,
          request_id: String
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_reader custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue]?

        def custom_fields_values=: (
          ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue]
        ) -> ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue]

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (
          id: Integer,
          ?custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue],
          ?name: String,
          ?request_id: String
        ) -> void

        def to_hash: -> {
          id: Integer,
          custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue],
          name: String,
          request_id: String
        }

        type custom_fields_value =
          {
            values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer,
            field_name: String,
            field_type: String
          }

        class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
          attr_accessor values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue::Value]

          attr_reader field_code: String?

          def field_code=: (String) -> String

          attr_reader field_id: Integer?

          def field_id=: (Integer) -> Integer

          attr_reader field_name: String?

          def field_name=: (String) -> String

          attr_reader field_type: String?

          def field_type=: (String) -> String

          def initialize: (
            values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue::Value],
            ?field_code: String,
            ?field_id: Integer,
            ?field_name: String,
            ?field_type: String
          ) -> void

          def to_hash: -> {
            values: ::Array[Amocrm::APICatalogElementsUpdateParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer,
            field_name: String,
            field_type: String
          }

          type value = { value: top, enum_code: String, enum_id: Integer }

          class Value < Amocrm::Internal::Type::BaseModel
            attr_accessor value: top

            attr_reader enum_code: String?

            def enum_code=: (String) -> String

            attr_reader enum_id: Integer?

            def enum_id=: (Integer) -> Integer

            def initialize: (
              value: top,
              ?enum_code: String,
              ?enum_id: Integer
            ) -> void

            def to_hash: -> { value: top, enum_code: String, enum_id: Integer }
          end
        end
      end
    end
  end
end
