module Amocrm
  module Models
    type call_create_response =
      Amocrm::Models::CallCreateResponse::CallCreateResponse
      | Amocrm::Models::CallCreateResponse::Problem

    module CallCreateResponse
      extend Amocrm::Internal::Type::Union

      type call_create_response =
        {
          _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded,
          _total_items: Integer,
          errors: ::Array[top]
        }

      class CallCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded
        ) -> Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded

        attr_reader _total_items: Integer?

        def _total_items=: (Integer) -> Integer

        attr_reader errors: ::Array[top]?

        def errors=: (::Array[top]) -> ::Array[top]

        def initialize: (
          ?_embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded,
          ?_total_items: Integer,
          ?errors: ::Array[top]
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded,
          _total_items: Integer,
          errors: ::Array[top]
        }

        type embedded =
          {
            calls: ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader calls: ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]?

          def calls=: (
            ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]
          ) -> ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]

          def initialize: (
            ?calls: ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]
          ) -> void

          def to_hash: -> {
            calls: ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call]
          }

          type call =
            {
              id: Integer,
              _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded,
              account_id: Integer,
              entity_id: Integer,
              entity_type: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type,
              request_id: String
            }

          class Call < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded?

            def _embedded=: (
              Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded
            ) -> Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded

            attr_reader account_id: Integer?

            def account_id=: (Integer) -> Integer

            attr_reader entity_id: Integer?

            def entity_id=: (Integer) -> Integer

            attr_reader entity_type: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type?

            def entity_type=: (
              Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type
            ) -> Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type

            attr_reader request_id: String?

            def request_id=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?_embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded,
              ?account_id: Integer,
              ?entity_id: Integer,
              ?entity_type: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type,
              ?request_id: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              _embedded: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded,
              account_id: Integer,
              entity_id: Integer,
              entity_type: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type,
              request_id: String
            }

            type embedded =
              {
                entity: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity
              }

            class Embedded < Amocrm::Internal::Type::BaseModel
              attr_reader entity: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity?

              def entity=: (
                Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity
              ) -> Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity

              def initialize: (
                ?entity: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity
              ) -> void

              def to_hash: -> {
                entity: Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::Embedded::Entity
              }

              type entity = { id: Integer, _links: top }

              class Entity < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end
            end

            type entity_type = String | Integer

            module EntityType
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::CallCreateResponse::CallCreateResponse::Embedded::Call::entity_type]
            end
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::call_create_response]
    end
  end
end
