module Amocrm
  module Models
    type call_create_params =
      { body: ::Array[Amocrm::CallCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class CallCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::CallCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::CallCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::CallCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          direction: Amocrm::Models::CallCreateParams::Body::direction,
          duration: Integer,
          phone: String,
          source: String,
          call_responsible: Amocrm::Models::CallCreateParams::Body::call_responsible?,
          call_result: String,
          call_status: Integer,
          created_at: Integer,
          created_by: Integer,
          link: String,
          request_id: String,
          responsible_user_id: Integer,
          uniq: String,
          updated_at: Integer,
          updated_by: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor direction: Amocrm::Models::CallCreateParams::Body::direction

        attr_accessor duration: Integer

        attr_accessor phone: String

        attr_accessor source: String

        attr_accessor call_responsible: Amocrm::Models::CallCreateParams::Body::call_responsible?

        attr_reader call_result: String?

        def call_result=: (String) -> String

        attr_reader call_status: Integer?

        def call_status=: (Integer) -> Integer

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader created_by: Integer?

        def created_by=: (Integer) -> Integer

        attr_reader link: String?

        def link=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader responsible_user_id: Integer?

        def responsible_user_id=: (Integer) -> Integer

        attr_reader uniq: String?

        def uniq=: (String) -> String

        attr_reader updated_at: Integer?

        def updated_at=: (Integer) -> Integer

        attr_reader updated_by: Integer?

        def updated_by=: (Integer) -> Integer

        def initialize: (
          direction: Amocrm::Models::CallCreateParams::Body::direction,
          duration: Integer,
          phone: String,
          source: String,
          ?call_responsible: Amocrm::Models::CallCreateParams::Body::call_responsible?,
          ?call_result: String,
          ?call_status: Integer,
          ?created_at: Integer,
          ?created_by: Integer,
          ?link: String,
          ?request_id: String,
          ?responsible_user_id: Integer,
          ?uniq: String,
          ?updated_at: Integer,
          ?updated_by: Integer
        ) -> void

        def to_hash: -> {
          direction: Amocrm::Models::CallCreateParams::Body::direction,
          duration: Integer,
          phone: String,
          source: String,
          call_responsible: Amocrm::Models::CallCreateParams::Body::call_responsible?,
          call_result: String,
          call_status: Integer,
          created_at: Integer,
          created_by: Integer,
          link: String,
          request_id: String,
          responsible_user_id: Integer,
          uniq: String,
          updated_at: Integer,
          updated_by: Integer
        }

        type direction = :inbound | :outbound | String

        module Direction
          extend Amocrm::Internal::Type::Union

          def self?.variants: -> ::Array[Amocrm::Models::CallCreateParams::Body::direction]

          INBOUND: :inbound
          OUTBOUND: :outbound
        end

        type call_responsible = String | Integer

        module CallResponsible
          extend Amocrm::Internal::Type::Union

          def self?.variants: -> ::Array[Amocrm::Models::CallCreateParams::Body::call_responsible]
        end
      end
    end
  end
end
