module Amocrm
  module Models
    type catalog_update_params =
      { body: ::Array[Amocrm::CatalogUpdateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class CatalogUpdateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::CatalogUpdateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::CatalogUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::CatalogUpdateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          id: Integer,
          can_add_elements: bool,
          can_link_multiple: bool,
          name: String,
          request_id: String,
          sort: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_reader can_add_elements: bool?

        def can_add_elements=: (bool) -> bool

        attr_reader can_link_multiple: bool?

        def can_link_multiple=: (bool) -> bool

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        def initialize: (
          id: Integer,
          ?can_add_elements: bool,
          ?can_link_multiple: bool,
          ?name: String,
          ?request_id: String,
          ?sort: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          can_add_elements: bool,
          can_link_multiple: bool,
          name: String,
          request_id: String,
          sort: Integer
        }
      end
    end
  end
end
