module Amocrm
  module Models
    type contact_chat_link_response =
      Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse
      | Amocrm::Models::ContactChatLinkResponse::Problem

    module ContactChatLinkResponse
      extend Amocrm::Internal::Type::Union

      type contact_chat_links_response =
        {
          _embedded: Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded,
          _links: top
        }

      class ContactChatLinksResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded
        ) -> Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            chats: ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader chats: ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]?

          def chats=: (
            ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]
          ) -> ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]

          def initialize: (
            ?chats: ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]
          ) -> void

          def to_hash: -> {
            chats: ::Array[Amocrm::Models::ContactChatLinkResponse::ContactChatLinksResponse::Embedded::Chat]
          }

          type chat =
            { chat_id: String, contact_id: Integer, request_id: String }

          class Chat < Amocrm::Internal::Type::BaseModel
            attr_accessor chat_id: String

            attr_accessor contact_id: Integer

            attr_reader request_id: String?

            def request_id=: (String) -> String

            def initialize: (
              chat_id: String,
              contact_id: Integer,
              ?request_id: String
            ) -> void

            def to_hash: -> {
              chat_id: String,
              contact_id: Integer,
              request_id: String
            }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::contact_chat_link_response]
    end
  end
end
