module Amocrm
  module Models
    type contact_list_response =
      Amocrm::Models::ContactListResponse::ContactListResponse
      | Amocrm::Models::ContactListResponse::Problem

    module ContactListResponse
      extend Amocrm::Internal::Type::Union

      type contact_list_response =
        {
          _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded,
          _links: top,
          _page: Integer
        }

      class ContactListResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::ContactListResponse::ContactListResponse::Embedded
        ) -> Amocrm::Models::ContactListResponse::ContactListResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        attr_reader _page: Integer?

        def _page=: (Integer) -> Integer

        def initialize: (
          ?_embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded,
          ?_links: top,
          ?_page: Integer
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded,
          _links: top,
          _page: Integer
        }

        type embedded =
          {
            contacts: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader contacts: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]?

          def contacts=: (
            ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]
          ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]

          def initialize: (
            ?contacts: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]
          ) -> void

          def to_hash: -> {
            contacts: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact]
          }

          type contact =
            {
              id: Integer,
              _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded,
              _links: top,
              account_id: Integer,
              closest_task_at: Integer,
              created_at: Integer,
              created_by: Integer,
              custom_fields_values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue]?,
              first_name: String,
              group_id: Integer,
              is_unsorted: bool,
              last_name: String,
              name: String,
              responsible_user_id: Integer,
              updated_at: Integer,
              updated_by: Integer
            }

          class Contact < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded?

            def _embedded=: (
              Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded
            ) -> Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader account_id: Integer?

            def account_id=: (Integer) -> Integer

            attr_reader closest_task_at: Integer?

            def closest_task_at=: (Integer) -> Integer

            attr_reader created_at: Integer?

            def created_at=: (Integer) -> Integer

            attr_reader created_by: Integer?

            def created_by=: (Integer) -> Integer

            attr_accessor custom_fields_values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue]?

            attr_reader first_name: String?

            def first_name=: (String) -> String

            attr_reader group_id: Integer?

            def group_id=: (Integer) -> Integer

            attr_reader is_unsorted: bool?

            def is_unsorted=: (bool) -> bool

            attr_reader last_name: String?

            def last_name=: (String) -> String

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader responsible_user_id: Integer?

            def responsible_user_id=: (Integer) -> Integer

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            attr_reader updated_by: Integer?

            def updated_by=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded,
              ?_links: top,
              ?account_id: Integer,
              ?closest_task_at: Integer,
              ?created_at: Integer,
              ?created_by: Integer,
              ?custom_fields_values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue]?,
              ?first_name: String,
              ?group_id: Integer,
              ?is_unsorted: bool,
              ?last_name: String,
              ?name: String,
              ?responsible_user_id: Integer,
              ?updated_at: Integer,
              ?updated_by: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              _embedded: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded,
              _links: top,
              account_id: Integer,
              closest_task_at: Integer,
              created_at: Integer,
              created_by: Integer,
              custom_fields_values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue]?,
              first_name: String,
              group_id: Integer,
              is_unsorted: bool,
              last_name: String,
              name: String,
              responsible_user_id: Integer,
              updated_at: Integer,
              updated_by: Integer
            }

            type embedded =
              {
                catalog_elements: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement],
                companies: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company],
                customers: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer],
                leads: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead],
                social_profiles: ::Array[top],
                tags: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]
              }

            class Embedded < Amocrm::Internal::Type::BaseModel
              attr_reader catalog_elements: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement]?

              def catalog_elements=: (
                ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement]
              ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement]

              attr_reader companies: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company]?

              def companies=: (
                ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company]
              ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company]

              attr_reader customers: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer]?

              def customers=: (
                ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer]
              ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer]

              attr_reader leads: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead]?

              def leads=: (
                ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead]
              ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead]

              attr_reader social_profiles: ::Array[top]?

              def social_profiles=: (::Array[top]) -> ::Array[top]

              attr_reader tags: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]?

              def tags=: (
                ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]
              ) -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]

              def initialize: (
                ?catalog_elements: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement],
                ?companies: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company],
                ?customers: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer],
                ?leads: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead],
                ?social_profiles: ::Array[top],
                ?tags: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]
              ) -> void

              def to_hash: -> {
                catalog_elements: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::CatalogElement],
                companies: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Company],
                customers: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Customer],
                leads: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Lead],
                social_profiles: ::Array[top],
                tags: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::Embedded::Tag]
              }

              type catalog_element = { id: Integer, _links: top }

              class CatalogElement < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type company = { id: Integer, _links: top }

              class Company < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type customer = { id: Integer, _links: top }

              class Customer < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type lead = { id: Integer, _links: top }

              class Lead < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader _links: top?

                def _links=: (top) -> top

                def initialize: (?id: Integer, ?_links: top) -> void

                def to_hash: -> { id: Integer, _links: top }
              end

              type tag = { id: Integer, color: String, name: String }

              class Tag < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader color: String?

                def color=: (String) -> String

                attr_reader name: String?

                def name=: (String) -> String

                def initialize: (
                  ?id: Integer,
                  ?color: String,
                  ?name: String
                ) -> void

                def to_hash: -> { id: Integer, color: String, name: String }
              end
            end

            type custom_fields_value =
              {
                values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

            class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
              attr_accessor values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value]

              attr_reader field_code: String?

              def field_code=: (String) -> String

              attr_reader field_id: Integer?

              def field_id=: (Integer) -> Integer

              def initialize: (
                values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value],
                ?field_code: String,
                ?field_id: Integer
              ) -> void

              def to_hash: -> {
                values: ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

              type value =
                {
                  value: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

              class Value < Amocrm::Internal::Type::BaseModel
                attr_accessor value: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value::value

                attr_reader enum_code: String?

                def enum_code=: (String) -> String

                attr_reader enum_id: Integer?

                def enum_id=: (Integer) -> Integer

                def initialize: (
                  value: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value::value,
                  ?enum_code: String,
                  ?enum_id: Integer
                ) -> void

                def to_hash: -> {
                  value: Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

                type value = String | Integer | bool

                module Value
                  extend Amocrm::Internal::Type::Union

                  def self?.variants: -> ::Array[Amocrm::Models::ContactListResponse::ContactListResponse::Embedded::Contact::CustomFieldsValue::Value::value]
                end
              end
            end
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::contact_list_response]
    end
  end
end
