module Amocrm
  module Models
    type customer_status_update_by_id_params =
      { color: String, name: String, sort: Integer }
      & Amocrm::Internal::Type::request_parameters

    class CustomerStatusUpdateByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader color: String?

      def color=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader sort: Integer?

      def sort=: (Integer) -> Integer

      def initialize: (
        ?color: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        color: String,
        name: String,
        sort: Integer,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
