module Amocrm
  module Models
    type customers_mode_set_mode_response =
      Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse
      | Amocrm::Models::CustomersModeSetModeResponse::Problem

    module CustomersModeSetModeResponse
      extend Amocrm::Internal::Type::Union

      type customer_mode_response =
        {
          is_enabled: bool,
          mode: Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode
        }

      class CustomerModeResponse < Amocrm::Internal::Type::BaseModel
        attr_reader is_enabled: bool?

        def is_enabled=: (bool) -> bool

        attr_reader mode: Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode?

        def mode=: (
          Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode
        ) -> Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode

        def initialize: (
          ?is_enabled: bool,
          ?mode: Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode
        ) -> void

        def to_hash: -> {
          is_enabled: bool,
          mode: Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode
        }

        type mode = :segments | :periodicity

        module Mode
          extend Amocrm::Internal::Type::Enum

          SEGMENTS: :segments
          PERIODICITY: :periodicity

          def self?.values: -> ::Array[Amocrm::Models::CustomersModeSetModeResponse::CustomerModeResponse::mode]
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::customers_mode_set_mode_response]
    end
  end
end
