module Amocrm
  module Models
    type custom_field_group_list_params =
      { entity_type: String, limit: Integer, page: Integer }
      & Amocrm::Internal::Type::request_parameters

    class CustomFieldGroupListParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor entity_type: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      def initialize: (
        entity_type: String,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        entity_type: String,
        limit: Integer,
        page: Integer,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
