module Amocrm
  module Models
    type customer_status_delete_by_id_params =
      { id: Integer } & Amocrm::Internal::Type::request_parameters

    class CustomerStatusDeleteByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor id: Integer

      def initialize: (
        id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> { id: Integer, request_options: Amocrm::RequestOptions }
    end
  end
end
