module Amocrm
  module Models
    type entity_note_list_params =
      { filter: top, limit: Integer, page: Integer }
      & Amocrm::Internal::Type::request_parameters

    class EntityNoteListParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader filter: top?

      def filter=: (top) -> top

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      def initialize: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        filter: top,
        limit: Integer,
        page: Integer,
        request_options: Amocrm::RequestOptions
      }

      type entity_type = :leads | :contacts | :companies | :customers

      module EntityType
        extend Amocrm::Internal::Type::Enum

        LEADS: :leads
        CONTACTS: :contacts
        COMPANIES: :companies
        CUSTOMERS: :customers

        def self?.values: -> ::Array[Amocrm::Models::EntityNoteListParams::entity_type]
      end
    end
  end
end
