module Amocrm
  module Models
    type entity_notes_by_parent_update_by_parent_id_response =
      Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse
      | Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::Problem

    module EntityNotesByParentUpdateByParentIDResponse
      extend Amocrm::Internal::Type::Union

      type note_create_response =
        {
          _embedded: Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded,
          _links: top
        }

      class NoteCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded
        ) -> Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            notes: ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader notes: ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]?

          def notes=: (
            ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]
          ) -> ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]

          def initialize: (
            ?notes: ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]
          ) -> void

          def to_hash: -> {
            notes: ::Array[Amocrm::Models::EntityNotesByParentUpdateByParentIDResponse::NoteCreateResponse::Embedded::Note]
          }

          type note =
            {
              id: Integer,
              _links: top,
              entity_id: Integer,
              request_id: String,
              updated_at: Integer
            }

          class Note < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader entity_id: Integer?

            def entity_id=: (Integer) -> Integer

            attr_reader request_id: String?

            def request_id=: (String) -> String

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?entity_id: Integer,
              ?request_id: String,
              ?updated_at: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              _links: top,
              entity_id: Integer,
              request_id: String,
              updated_at: Integer
            }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::entity_notes_by_parent_update_by_parent_id_response]
    end
  end
end
