module Amocrm
  module Models
    type entity_link_list_params =
      { filter: top } & Amocrm::Internal::Type::request_parameters

    class EntityLinkListParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader filter: top?

      def filter=: (top) -> top

      def initialize: (
        ?filter: top,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> { filter: top, request_options: Amocrm::RequestOptions }

      type entity_type = :leads | :contacts | :companies | :customers

      module EntityType
        extend Amocrm::Internal::Type::Enum

        LEADS: :leads
        CONTACTS: :contacts
        COMPANIES: :companies
        CUSTOMERS: :customers

        def self?.values: -> ::Array[Amocrm::Models::EntityLinkListParams::entity_type]
      end
    end
  end
end
