module Amocrm
  module Models
    type entity_note_create_params =
      { body: ::Array[Amocrm::EntityNoteCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class EntityNoteCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::EntityNoteCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::EntityNoteCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::EntityNoteCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type entity_type = :leads | :contacts | :companies | :customers

      module EntityType
        extend Amocrm::Internal::Type::Enum

        LEADS: :leads
        CONTACTS: :contacts
        COMPANIES: :companies
        CUSTOMERS: :customers

        def self?.values: -> ::Array[Amocrm::Models::EntityNoteCreateParams::entity_type]
      end

      type body =
        {
          note_type: String,
          created_at: Integer,
          created_by: Integer,
          entity_id: Integer,
          is_need_to_trigger_digital_pipeline: bool,
          params: top,
          request_id: String,
          responsible_user_id: Integer,
          updated_by: Integer
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor note_type: String

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader created_by: Integer?

        def created_by=: (Integer) -> Integer

        attr_reader entity_id: Integer?

        def entity_id=: (Integer) -> Integer

        attr_reader is_need_to_trigger_digital_pipeline: bool?

        def is_need_to_trigger_digital_pipeline=: (bool) -> bool

        attr_reader params: top?

        def params=: (top) -> top

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader responsible_user_id: Integer?

        def responsible_user_id=: (Integer) -> Integer

        attr_reader updated_by: Integer?

        def updated_by=: (Integer) -> Integer

        def initialize: (
          note_type: String,
          ?created_at: Integer,
          ?created_by: Integer,
          ?entity_id: Integer,
          ?is_need_to_trigger_digital_pipeline: bool,
          ?params: top,
          ?request_id: String,
          ?responsible_user_id: Integer,
          ?updated_by: Integer
        ) -> void

        def to_hash: -> {
          note_type: String,
          created_at: Integer,
          created_by: Integer,
          entity_id: Integer,
          is_need_to_trigger_digital_pipeline: bool,
          params: top,
          request_id: String,
          responsible_user_id: Integer,
          updated_by: Integer
        }
      end
    end
  end
end
