module Amocrm
  module Models
    type event_list_types_response =
      Amocrm::Models::EventListTypesResponse::EventTypesResponse
      | Amocrm::Models::EventListTypesResponse::Problem

    module EventListTypesResponse
      extend Amocrm::Internal::Type::Union

      type event_types_response =
        {
          _embedded: Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded
        }

      class EventTypesResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded
        ) -> Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded

        def initialize: (
          ?_embedded: Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::EventListTypesResponse::EventTypesResponse::Embedded
        }

        type embedded = { types: ::Array[top] }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader types: ::Array[top]?

          def types=: (::Array[top]) -> ::Array[top]

          def initialize: (?types: ::Array[top]) -> void

          def to_hash: -> { types: ::Array[top] }
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::event_list_types_response]
    end
  end
end
