module Amocrm
  module Models
    type lead_list_response =
      Amocrm::Models::LeadListResponse::LeadListResponse
      | Amocrm::Models::LeadListResponse::Problem

    module LeadListResponse
      extend Amocrm::Internal::Type::Union

      type lead_list_response =
        {
          _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded,
          _links: top,
          _page: Integer
        }

      class LeadListResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::LeadListResponse::LeadListResponse::Embedded
        ) -> Amocrm::Models::LeadListResponse::LeadListResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        attr_reader _page: Integer?

        def _page=: (Integer) -> Integer

        def initialize: (
          ?_embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded,
          ?_links: top,
          ?_page: Integer
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded,
          _links: top,
          _page: Integer
        }

        type embedded =
          {
            leads: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader leads: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]?

          def leads=: (
            ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]
          ) -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]

          def initialize: (
            ?leads: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]
          ) -> void

          def to_hash: -> {
            leads: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead]
          }

          type lead =
            {
              id: Integer,
              _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded,
              _links: top,
              account_id: Integer,
              closed_at: Integer,
              closest_task_at: Integer,
              created_at: Integer,
              created_by: Integer,
              custom_fields_values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue]?,
              group_id: Integer,
              is_deleted: bool,
              is_price_modified_by_robot: bool,
              labor_cost: Integer,
              loss_reason_id: Integer,
              name: String,
              pipeline_id: Integer,
              price: Integer,
              responsible_user_id: Integer,
              score: Integer?,
              source_id: Integer,
              status_id: Integer,
              updated_at: Integer,
              updated_by: Integer,
              visitor_uid: String
            }

          class Lead < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded?

            def _embedded=: (
              Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded
            ) -> Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader account_id: Integer?

            def account_id=: (Integer) -> Integer

            attr_reader closed_at: Integer?

            def closed_at=: (Integer) -> Integer

            attr_reader closest_task_at: Integer?

            def closest_task_at=: (Integer) -> Integer

            attr_reader created_at: Integer?

            def created_at=: (Integer) -> Integer

            attr_reader created_by: Integer?

            def created_by=: (Integer) -> Integer

            attr_accessor custom_fields_values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue]?

            attr_reader group_id: Integer?

            def group_id=: (Integer) -> Integer

            attr_reader is_deleted: bool?

            def is_deleted=: (bool) -> bool

            attr_reader is_price_modified_by_robot: bool?

            def is_price_modified_by_robot=: (bool) -> bool

            attr_reader labor_cost: Integer?

            def labor_cost=: (Integer) -> Integer

            attr_reader loss_reason_id: Integer?

            def loss_reason_id=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader pipeline_id: Integer?

            def pipeline_id=: (Integer) -> Integer

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader responsible_user_id: Integer?

            def responsible_user_id=: (Integer) -> Integer

            attr_accessor score: Integer?

            attr_reader source_id: Integer?

            def source_id=: (Integer) -> Integer

            attr_reader status_id: Integer?

            def status_id=: (Integer) -> Integer

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            attr_reader updated_by: Integer?

            def updated_by=: (Integer) -> Integer

            attr_reader visitor_uid: String?

            def visitor_uid=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?_embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded,
              ?_links: top,
              ?account_id: Integer,
              ?closed_at: Integer,
              ?closest_task_at: Integer,
              ?created_at: Integer,
              ?created_by: Integer,
              ?custom_fields_values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue]?,
              ?group_id: Integer,
              ?is_deleted: bool,
              ?is_price_modified_by_robot: bool,
              ?labor_cost: Integer,
              ?loss_reason_id: Integer,
              ?name: String,
              ?pipeline_id: Integer,
              ?price: Integer,
              ?responsible_user_id: Integer,
              ?score: Integer?,
              ?source_id: Integer,
              ?status_id: Integer,
              ?updated_at: Integer,
              ?updated_by: Integer,
              ?visitor_uid: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              _embedded: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded,
              _links: top,
              account_id: Integer,
              closed_at: Integer,
              closest_task_at: Integer,
              created_at: Integer,
              created_by: Integer,
              custom_fields_values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue]?,
              group_id: Integer,
              is_deleted: bool,
              is_price_modified_by_robot: bool,
              labor_cost: Integer,
              loss_reason_id: Integer,
              name: String,
              pipeline_id: Integer,
              price: Integer,
              responsible_user_id: Integer,
              score: Integer?,
              source_id: Integer,
              status_id: Integer,
              updated_at: Integer,
              updated_by: Integer,
              visitor_uid: String
            }

            type embedded =
              {
                catalog_elements: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement],
                companies: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company],
                contacts: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact],
                loss_reason: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason,
                source: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source,
                tags: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]
              }

            class Embedded < Amocrm::Internal::Type::BaseModel
              attr_reader catalog_elements: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement]?

              def catalog_elements=: (
                ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement]
              ) -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement]

              attr_reader companies: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company]?

              def companies=: (
                ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company]
              ) -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company]

              attr_reader contacts: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact]?

              def contacts=: (
                ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact]
              ) -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact]

              attr_reader loss_reason: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason?

              def loss_reason=: (
                Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason
              ) -> Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason

              attr_reader source: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source?

              def source=: (
                Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source
              ) -> Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source

              attr_reader tags: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]?

              def tags=: (
                ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]
              ) -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]

              def initialize: (
                ?catalog_elements: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement],
                ?companies: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company],
                ?contacts: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact],
                ?loss_reason: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason,
                ?source: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source,
                ?tags: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]
              ) -> void

              def to_hash: -> {
                catalog_elements: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::CatalogElement],
                companies: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Company],
                contacts: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Contact],
                loss_reason: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::LossReason,
                source: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source,
                tags: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Tag]
              }

              type catalog_element = { id: Integer, metadata: top }

              class CatalogElement < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader metadata: top?

                def metadata=: (top) -> top

                def initialize: (?id: Integer, ?metadata: top) -> void

                def to_hash: -> { id: Integer, metadata: top }
              end

              type company = { id: Integer }

              class Company < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                def initialize: (?id: Integer) -> void

                def to_hash: -> { id: Integer }
              end

              type contact = { id: Integer, is_main: bool }

              class Contact < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader is_main: bool?

                def is_main=: (bool) -> bool

                def initialize: (?id: Integer, ?is_main: bool) -> void

                def to_hash: -> { id: Integer, is_main: bool }
              end

              type loss_reason = { id: Integer, name: String }

              class LossReason < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader name: String?

                def name=: (String) -> String

                def initialize: (?id: Integer, ?name: String) -> void

                def to_hash: -> { id: Integer, name: String }
              end

              type source =
                {
                  external_id: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id,
                  type: String
                }

              class Source < Amocrm::Internal::Type::BaseModel
                attr_reader external_id: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id?

                def external_id=: (
                  Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id
                ) -> Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id

                attr_reader type: String?

                def type=: (String) -> String

                def initialize: (
                  ?external_id: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id,
                  ?type: String
                ) -> void

                def to_hash: -> {
                  external_id: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id,
                  type: String
                }

                type external_id = String | Integer | bool

                module ExternalID
                  extend Amocrm::Internal::Type::Union

                  def self?.variants: -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::Embedded::Source::external_id]
                end
              end

              type tag = { id: Integer, color: String, name: String }

              class Tag < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader color: String?

                def color=: (String) -> String

                attr_reader name: String?

                def name=: (String) -> String

                def initialize: (
                  ?id: Integer,
                  ?color: String,
                  ?name: String
                ) -> void

                def to_hash: -> { id: Integer, color: String, name: String }
              end
            end

            type custom_fields_value =
              {
                values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

            class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
              attr_accessor values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value]

              attr_reader field_code: String?

              def field_code=: (String) -> String

              attr_reader field_id: Integer?

              def field_id=: (Integer) -> Integer

              def initialize: (
                values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value],
                ?field_code: String,
                ?field_id: Integer
              ) -> void

              def to_hash: -> {
                values: ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

              type value =
                {
                  value: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

              class Value < Amocrm::Internal::Type::BaseModel
                attr_accessor value: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value::value

                attr_reader enum_code: String?

                def enum_code=: (String) -> String

                attr_reader enum_id: Integer?

                def enum_id=: (Integer) -> Integer

                def initialize: (
                  value: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value::value,
                  ?enum_code: String,
                  ?enum_id: Integer
                ) -> void

                def to_hash: -> {
                  value: Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

                type value = String | Integer | bool

                module Value
                  extend Amocrm::Internal::Type::Union

                  def self?.variants: -> ::Array[Amocrm::Models::LeadListResponse::LeadListResponse::Embedded::Lead::CustomFieldsValue::Value::value]
                end
              end
            end
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::lead_list_response]
    end
  end
end
