module Amocrm
  module Models
    type pet_update_with_form_params =
      { name: String, status: String }
      & Amocrm::Internal::Type::request_parameters

    class PetUpdateWithFormParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      def initialize: (
        ?name: String,
        ?status: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        status: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
