module Amocrm
  module Models
    type pet_find_by_status_params =
      { status: Amocrm::Models::PetFindByStatusParams::status }
      & Amocrm::Internal::Type::request_parameters

    class PetFindByStatusParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader status: Amocrm::Models::PetFindByStatusParams::status?

      def status=: (
        Amocrm::Models::PetFindByStatusParams::status
      ) -> Amocrm::Models::PetFindByStatusParams::status

      def initialize: (
        ?status: Amocrm::Models::PetFindByStatusParams::status,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        status: Amocrm::Models::PetFindByStatusParams::status,
        request_options: Amocrm::RequestOptions
      }

      type status = :available | :pending | :sold

      module Status
        extend Amocrm::Internal::Type::Enum

        AVAILABLE: :available
        PENDING: :pending
        SOLD: :sold

        def self?.values: -> ::Array[Amocrm::Models::PetFindByStatusParams::status]
      end
    end
  end
end
