module Amocrm
  module Models
    type pipeline_status_get_by_id_params =
      { pipeline_id: Integer, with: String }
      & Amocrm::Internal::Type::request_parameters

    class PipelineStatusGetByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor pipeline_id: Integer

      attr_reader with: String?

      def with=: (String) -> String

      def initialize: (
        pipeline_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        pipeline_id: Integer,
        with: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
