module Amocrm
  module Models
    type pipeline_status_delete_by_id_params =
      { pipeline_id: Integer } & Amocrm::Internal::Type::request_parameters

    class PipelineStatusDeleteByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor pipeline_id: Integer

      def initialize: (
        pipeline_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        pipeline_id: Integer,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
