module Amocrm
  module Models
    type talk_close_params =
      { id: Integer, force_close: bool }
      & Amocrm::Internal::Type::request_parameters

    class TalkCloseParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor id: Integer

      attr_reader force_close: bool?

      def force_close=: (bool) -> bool

      def initialize: (
        id: Integer,
        ?force_close: bool,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        id: Integer,
        force_close: bool,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
