module Amocrm
  module Models
    type task_update_params =
      { body: ::Array[Amocrm::TaskUpdateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class TaskUpdateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::TaskUpdateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::TaskUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::TaskUpdateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          id: Integer,
          complete_till: Integer,
          entity_id: Integer,
          entity_type: String,
          is_completed: bool,
          responsible_user_id: Integer,
          result: Amocrm::TaskUpdateParams::Body::Result,
          task_type_id: Integer,
          text: String
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor id: Integer

        attr_reader complete_till: Integer?

        def complete_till=: (Integer) -> Integer

        attr_reader entity_id: Integer?

        def entity_id=: (Integer) -> Integer

        attr_reader entity_type: String?

        def entity_type=: (String) -> String

        attr_reader is_completed: bool?

        def is_completed=: (bool) -> bool

        attr_reader responsible_user_id: Integer?

        def responsible_user_id=: (Integer) -> Integer

        attr_reader result: Amocrm::TaskUpdateParams::Body::Result?

        def result=: (
          Amocrm::TaskUpdateParams::Body::Result
        ) -> Amocrm::TaskUpdateParams::Body::Result

        attr_reader task_type_id: Integer?

        def task_type_id=: (Integer) -> Integer

        attr_reader text: String?

        def text=: (String) -> String

        def initialize: (
          id: Integer,
          ?complete_till: Integer,
          ?entity_id: Integer,
          ?entity_type: String,
          ?is_completed: bool,
          ?responsible_user_id: Integer,
          ?result: Amocrm::TaskUpdateParams::Body::Result,
          ?task_type_id: Integer,
          ?text: String
        ) -> void

        def to_hash: -> {
          id: Integer,
          complete_till: Integer,
          entity_id: Integer,
          entity_type: String,
          is_completed: bool,
          responsible_user_id: Integer,
          result: Amocrm::TaskUpdateParams::Body::Result,
          task_type_id: Integer,
          text: String
        }

        type result = { text: String }

        class Result < Amocrm::Internal::Type::BaseModel
          attr_reader text: String?

          def text=: (String) -> String

          def initialize: (?text: String) -> void

          def to_hash: -> { text: String }
        end
      end
    end
  end
end
