module Amocrm
  module Models
    type user_login_params =
      { password: String, username: String }
      & Amocrm::Internal::Type::request_parameters

    class UserLoginParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader password: String?

      def password=: (String) -> String

      attr_reader username: String?

      def username=: (String) -> String

      def initialize: (
        ?password: String,
        ?username: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        password: String,
        username: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
