module Amocrm
  module Models
    type user_update_params = {  } & Amocrm::Internal::Type::request_parameters

    class UserUpdateParams < Amocrm::Models::UserAPI
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      def initialize: (?request_options: Amocrm::request_opts) -> void

      def to_hash: -> { request_options: Amocrm::RequestOptions }
    end
  end
end
