module Amocrm
  module Models
    type v2_salesbot_run_params =
      { body: ::Array[Amocrm::V2SalesbotRunParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class V2SalesbotRunParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::V2SalesbotRunParams::Body]

      def initialize: (
        body: ::Array[Amocrm::V2SalesbotRunParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::V2SalesbotRunParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body = { bot_id: Integer, entity_id: Integer, entity_type: Integer }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor bot_id: Integer

        attr_accessor entity_id: Integer

        attr_accessor entity_type: Integer

        def initialize: (
          bot_id: Integer,
          entity_id: Integer,
          entity_type: Integer
        ) -> void

        def to_hash: -> {
          bot_id: Integer,
          entity_id: Integer,
          entity_type: Integer
        }
      end
    end
  end
end
