module Amocrm
  module Models
    type v4_companies_update_response =
      Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse
      | Amocrm::Models::V4CompaniesUpdateResponse::Problem

    module V4CompaniesUpdateResponse
      extend Amocrm::Internal::Type::Union

      type company_update_response =
        {
          _embedded: Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded,
          _links: top
        }

      class CompanyUpdateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded
        ) -> Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            companies: ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader companies: ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]?

          def companies=: (
            ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]
          ) -> ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]

          def initialize: (
            ?companies: ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]
          ) -> void

          def to_hash: -> {
            companies: ::Array[Amocrm::Models::V4CompaniesUpdateResponse::CompanyUpdateResponse::Embedded::Company]
          }

          type company = { id: Integer, _links: top, updated_at: Integer }

          class Company < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader updated_at: Integer?

            def updated_at=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?updated_at: Integer
            ) -> void

            def to_hash: -> { id: Integer, _links: top, updated_at: Integer }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::v4_companies_update_response]
    end
  end
end
