module Amocrm
  module Models
    type v4_catalog_elements_list_params =
      {
        filter: top,
        limit: Integer,
        page: Integer,
        query: Amocrm::Models::V4CatalogElementsListParams::query
      }
      & Amocrm::Internal::Type::request_parameters

    class V4CatalogElementsListParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader filter: top?

      def filter=: (top) -> top

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader page: Integer?

      def page=: (Integer) -> Integer

      attr_reader query: Amocrm::Models::V4CatalogElementsListParams::query?

      def query=: (
        Amocrm::Models::V4CatalogElementsListParams::query
      ) -> Amocrm::Models::V4CatalogElementsListParams::query

      def initialize: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?query: Amocrm::Models::V4CatalogElementsListParams::query,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        filter: top,
        limit: Integer,
        page: Integer,
        query: Amocrm::Models::V4CatalogElementsListParams::query,
        request_options: Amocrm::RequestOptions
      }

      type query = String | Integer

      module Query
        extend Amocrm::Internal::Type::Union

        def self?.variants: -> ::Array[Amocrm::Models::V4CatalogElementsListParams::query]
      end
    end
  end
end
