module Amocrm
  module Models
    type v4_catalogs_update_by_id_params =
      {
        can_add_elements: bool,
        can_link_multiple: bool,
        name: String,
        request_id: String,
        sort: Integer
      }
      & Amocrm::Internal::Type::request_parameters

    class V4CatalogsUpdateByIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_reader can_add_elements: bool?

      def can_add_elements=: (bool) -> bool

      attr_reader can_link_multiple: bool?

      def can_link_multiple=: (bool) -> bool

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader request_id: String?

      def request_id=: (String) -> String

      attr_reader sort: Integer?

      def sort=: (Integer) -> Integer

      def initialize: (
        ?can_add_elements: bool,
        ?can_link_multiple: bool,
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        can_add_elements: bool,
        can_link_multiple: bool,
        name: String,
        request_id: String,
        sort: Integer,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
