module Amocrm
  module Models
    type v4_entity_links_unlink_by_entity_params =
      {
        entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type,
        body: ::Array[Amocrm::V4EntityLinksUnlinkByEntityParams::Body]
      }
      & Amocrm::Internal::Type::request_parameters

    class V4EntityLinksUnlinkByEntityParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type

      attr_accessor body: ::Array[Amocrm::V4EntityLinksUnlinkByEntityParams::Body]

      def initialize: (
        entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type,
        body: ::Array[Amocrm::V4EntityLinksUnlinkByEntityParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type,
        body: ::Array[Amocrm::V4EntityLinksUnlinkByEntityParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type entity_type = :leads | :contacts | :companies | :customers

      module EntityType
        extend Amocrm::Internal::Type::Enum

        LEADS: :leads
        CONTACTS: :contacts
        COMPANIES: :companies
        CUSTOMERS: :customers

        def self?.values: -> ::Array[Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type]
      end

      type body =
        {
          entity_id: Integer,
          entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type,
          metadata: top,
          to_entity_id: Integer,
          to_entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_reader entity_id: Integer?

        def entity_id=: (Integer) -> Integer

        attr_reader entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type?

        def entity_type=: (
          Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type
        ) -> Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type

        attr_reader metadata: top?

        def metadata=: (top) -> top

        attr_reader to_entity_id: Integer?

        def to_entity_id=: (Integer) -> Integer

        attr_reader to_entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type?

        def to_entity_type=: (
          Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type
        ) -> Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type

        def initialize: (
          ?entity_id: Integer,
          ?entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type,
          ?metadata: top,
          ?to_entity_id: Integer,
          ?to_entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type
        ) -> void

        def to_hash: -> {
          entity_id: Integer,
          entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type,
          metadata: top,
          to_entity_id: Integer,
          to_entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type
        }

        type entity_type = :leads | :contacts | :companies | :customers | String

        module EntityType
          extend Amocrm::Internal::Type::Union

          def self?.variants: -> ::Array[Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::entity_type]

          LEADS: :leads
          CONTACTS: :contacts
          COMPANIES: :companies
          CUSTOMERS: :customers
        end

        type to_entity_type =
          :leads | :contacts | :companies | :customers | String

        module ToEntityType
          extend Amocrm::Internal::Type::Union

          def self?.variants: -> ::Array[Amocrm::Models::V4EntityLinksUnlinkByEntityParams::Body::to_entity_type]

          LEADS: :leads
          CONTACTS: :contacts
          COMPANIES: :companies
          CUSTOMERS: :customers
        end
      end
    end
  end
end
