module Amocrm
  module Models
    type v4_entity_notes_by_parent_get_by_parent_id_params =
      {
        entity_type: Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type,
        entity_id: Integer,
        with: String
      }
      & Amocrm::Internal::Type::request_parameters

    class V4EntityNotesByParentGetByParentIDParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor entity_type: Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type

      attr_accessor entity_id: Integer

      attr_reader with: String?

      def with=: (String) -> String

      def initialize: (
        entity_type: Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type,
        entity_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        entity_type: Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type,
        entity_id: Integer,
        with: String,
        request_options: Amocrm::RequestOptions
      }

      type entity_type = :leads | :contacts | :companies | :customers

      module EntityType
        extend Amocrm::Internal::Type::Enum

        LEADS: :leads
        CONTACTS: :contacts
        COMPANIES: :companies
        CUSTOMERS: :customers

        def self?.values: -> ::Array[Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type]
      end
    end
  end
end
