module Amocrm
  module Models
    type v4_leads_create_complex_params =
      { body: ::Array[Amocrm::V4LeadsCreateComplexParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class V4LeadsCreateComplexParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::V4LeadsCreateComplexParams::Body]

      def initialize: (
        body: ::Array[Amocrm::V4LeadsCreateComplexParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::V4LeadsCreateComplexParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          _embedded: Amocrm::V4LeadsCreateComplexParams::Body::Embedded,
          closed_at: Integer,
          created_at: Integer,
          created_by: Integer,
          custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue],
          group_id: Integer,
          loss_reason_id: Integer,
          name: String,
          pipeline_id: Integer,
          price: Integer,
          request_id: String,
          responsible_user_id: Integer,
          status_id: Integer,
          tags_to_add: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd],
          updated_at: Integer,
          updated_by: Integer,
          visitor_uid: String
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::V4LeadsCreateComplexParams::Body::Embedded?

        def _embedded=: (
          Amocrm::V4LeadsCreateComplexParams::Body::Embedded
        ) -> Amocrm::V4LeadsCreateComplexParams::Body::Embedded

        attr_reader closed_at: Integer?

        def closed_at=: (Integer) -> Integer

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_reader created_by: Integer?

        def created_by=: (Integer) -> Integer

        attr_reader custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue]?

        def custom_fields_values=: (
          ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue]
        ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue]

        attr_reader group_id: Integer?

        def group_id=: (Integer) -> Integer

        attr_reader loss_reason_id: Integer?

        def loss_reason_id=: (Integer) -> Integer

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader pipeline_id: Integer?

        def pipeline_id=: (Integer) -> Integer

        attr_reader price: Integer?

        def price=: (Integer) -> Integer

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader responsible_user_id: Integer?

        def responsible_user_id=: (Integer) -> Integer

        attr_reader status_id: Integer?

        def status_id=: (Integer) -> Integer

        attr_reader tags_to_add: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd]?

        def tags_to_add=: (
          ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd]
        ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd]

        attr_reader updated_at: Integer?

        def updated_at=: (Integer) -> Integer

        attr_reader updated_by: Integer?

        def updated_by=: (Integer) -> Integer

        attr_reader visitor_uid: String?

        def visitor_uid=: (String) -> String

        def initialize: (
          ?_embedded: Amocrm::V4LeadsCreateComplexParams::Body::Embedded,
          ?closed_at: Integer,
          ?created_at: Integer,
          ?created_by: Integer,
          ?custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue],
          ?group_id: Integer,
          ?loss_reason_id: Integer,
          ?name: String,
          ?pipeline_id: Integer,
          ?price: Integer,
          ?request_id: String,
          ?responsible_user_id: Integer,
          ?status_id: Integer,
          ?tags_to_add: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd],
          ?updated_at: Integer,
          ?updated_by: Integer,
          ?visitor_uid: String
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::V4LeadsCreateComplexParams::Body::Embedded,
          closed_at: Integer,
          created_at: Integer,
          created_by: Integer,
          custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue],
          group_id: Integer,
          loss_reason_id: Integer,
          name: String,
          pipeline_id: Integer,
          price: Integer,
          request_id: String,
          responsible_user_id: Integer,
          status_id: Integer,
          tags_to_add: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::TagsToAdd],
          updated_at: Integer,
          updated_by: Integer,
          visitor_uid: String
        }

        type embedded =
          {
            companies: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company],
            contacts: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact],
            metadata: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata,
            source: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source,
            tags: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader companies: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company]?

          def companies=: (
            ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company]
          ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company]

          attr_reader contacts: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact]?

          def contacts=: (
            ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact]
          ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact]

          attr_reader metadata: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata?

          def metadata=: (
            Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata
          ) -> Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata

          attr_reader source: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source?

          def source=: (
            Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source
          ) -> Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source

          attr_reader tags: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]?

          def tags=: (
            ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]
          ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]

          def initialize: (
            ?companies: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company],
            ?contacts: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact],
            ?metadata: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata,
            ?source: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source,
            ?tags: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]
          ) -> void

          def to_hash: -> {
            companies: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Company],
            contacts: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact],
            metadata: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Metadata,
            source: Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Source,
            tags: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Tag]
          }

          type company = { id: Integer, name: String }

          class Company < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader name: String?

            def name=: (String) -> String

            def initialize: (?id: Integer, ?name: String) -> void

            def to_hash: -> { id: Integer, name: String }
          end

          type contact =
            {
              id: Integer,
              custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue],
              first_name: String,
              last_name: String,
              name: String
            }

          class Contact < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue]?

            def custom_fields_values=: (
              ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue]
            ) -> ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue]

            attr_reader first_name: String?

            def first_name=: (String) -> String

            attr_reader last_name: String?

            def last_name=: (String) -> String

            attr_reader name: String?

            def name=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue],
              ?first_name: String,
              ?last_name: String,
              ?name: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              custom_fields_values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue],
              first_name: String,
              last_name: String,
              name: String
            }

            type custom_fields_value =
              {
                values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

            class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
              attr_accessor values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value]

              attr_reader field_code: String?

              def field_code=: (String) -> String

              attr_reader field_id: Integer?

              def field_id=: (Integer) -> Integer

              def initialize: (
                values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value],
                ?field_code: String,
                ?field_id: Integer
              ) -> void

              def to_hash: -> {
                values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value],
                field_code: String,
                field_id: Integer
              }

              type value =
                {
                  value: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

              class Value < Amocrm::Internal::Type::BaseModel
                attr_accessor value: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value::value

                attr_reader enum_code: String?

                def enum_code=: (String) -> String

                attr_reader enum_id: Integer?

                def enum_id=: (Integer) -> Integer

                def initialize: (
                  value: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value::value,
                  ?enum_code: String,
                  ?enum_id: Integer
                ) -> void

                def to_hash: -> {
                  value: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value::value,
                  enum_code: String,
                  enum_id: Integer
                }

                type value = String | Integer | bool

                module Value
                  extend Amocrm::Internal::Type::Union

                  def self?.variants: -> ::Array[Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Contact::CustomFieldsValue::Value::value]
                end
              end
            end
          end

          type metadata =
            {
              category: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category,
              form_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id,
              form_name: String,
              form_page: String,
              form_sent_at: Integer,
              form_type: Integer,
              ip: String,
              referer: String,
              visitor_uid: String
            }

          class Metadata < Amocrm::Internal::Type::BaseModel
            attr_reader category: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category?

            def category=: (
              Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category
            ) -> Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category

            attr_reader form_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id?

            def form_id=: (
              Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id
            ) -> Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id

            attr_reader form_name: String?

            def form_name=: (String) -> String

            attr_reader form_page: String?

            def form_page=: (String) -> String

            attr_reader form_sent_at: Integer?

            def form_sent_at=: (Integer) -> Integer

            attr_reader form_type: Integer?

            def form_type=: (Integer) -> Integer

            attr_reader ip: String?

            def ip=: (String) -> String

            attr_reader referer: String?

            def referer=: (String) -> String

            attr_reader visitor_uid: String?

            def visitor_uid=: (String) -> String

            def initialize: (
              ?category: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category,
              ?form_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id,
              ?form_name: String,
              ?form_page: String,
              ?form_sent_at: Integer,
              ?form_type: Integer,
              ?ip: String,
              ?referer: String,
              ?visitor_uid: String
            ) -> void

            def to_hash: -> {
              category: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category,
              form_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id,
              form_name: String,
              form_page: String,
              form_sent_at: Integer,
              form_type: Integer,
              ip: String,
              referer: String,
              visitor_uid: String
            }

            type category = :sip | :forms | :chats | :mail

            module Category
              extend Amocrm::Internal::Type::Enum

              SIP: :sip
              FORMS: :forms
              CHATS: :chats
              MAIL: :mail

              def self?.values: -> ::Array[Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::category]
            end

            type form_id = String | Integer

            module FormID
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Metadata::form_id]
            end
          end

          type source =
            {
              external_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id,
              type: String
            }

          class Source < Amocrm::Internal::Type::BaseModel
            attr_reader external_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id?

            def external_id=: (
              Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id
            ) -> Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?external_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id,
              ?type: String
            ) -> void

            def to_hash: -> {
              external_id: Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id,
              type: String
            }

            type external_id = String | Integer | bool

            module ExternalID
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::V4LeadsCreateComplexParams::Body::Embedded::Source::external_id]
            end
          end

          type tag = { id: Integer, color: String, name: String }

          class Tag < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader color: String?

            def color=: (String) -> String

            attr_reader name: String?

            def name=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?color: String,
              ?name: String
            ) -> void

            def to_hash: -> { id: Integer, color: String, name: String }
          end
        end

        type custom_fields_value =
          {
            values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer
          }

        class CustomFieldsValue < Amocrm::Internal::Type::BaseModel
          attr_accessor values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value]

          attr_reader field_code: String?

          def field_code=: (String) -> String

          attr_reader field_id: Integer?

          def field_id=: (Integer) -> Integer

          def initialize: (
            values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value],
            ?field_code: String,
            ?field_id: Integer
          ) -> void

          def to_hash: -> {
            values: ::Array[Amocrm::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value],
            field_code: String,
            field_id: Integer
          }

          type value =
            {
              value: Amocrm::Models::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value::value,
              enum_code: String,
              enum_id: Integer
            }

          class Value < Amocrm::Internal::Type::BaseModel
            attr_accessor value: Amocrm::Models::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value::value

            attr_reader enum_code: String?

            def enum_code=: (String) -> String

            attr_reader enum_id: Integer?

            def enum_id=: (Integer) -> Integer

            def initialize: (
              value: Amocrm::Models::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value::value,
              ?enum_code: String,
              ?enum_id: Integer
            ) -> void

            def to_hash: -> {
              value: Amocrm::Models::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value::value,
              enum_code: String,
              enum_id: Integer
            }

            type value = String | Integer | bool

            module Value
              extend Amocrm::Internal::Type::Union

              def self?.variants: -> ::Array[Amocrm::Models::V4LeadsCreateComplexParams::Body::CustomFieldsValue::Value::value]
            end
          end
        end

        type tags_to_add = { id: Integer, color: String, name: String }

        class TagsToAdd < Amocrm::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader color: String?

          def color=: (String) -> String

          attr_reader name: String?

          def name=: (String) -> String

          def initialize: (?id: Integer, ?color: String, ?name: String) -> void

          def to_hash: -> { id: Integer, color: String, name: String }
        end
      end
    end
  end
end
