module Amocrm
  module Models
    type v4_pipelines_list_response =
      Amocrm::Models::V4PipelinesListResponse::PipelineListResponse
      | Amocrm::Models::V4PipelinesListResponse::Problem

    module V4PipelinesListResponse
      extend Amocrm::Internal::Type::Union

      type pipeline_list_response =
        {
          _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded,
          _links: top
        }

      class PipelineListResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded
        ) -> Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            pipelines: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader pipelines: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]?

          def pipelines=: (
            ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]
          ) -> ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]

          def initialize: (
            ?pipelines: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]
          ) -> void

          def to_hash: -> {
            pipelines: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline]
          }

          type pipeline =
            {
              id: Integer,
              _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded,
              _links: top,
              account_id: Integer,
              is_archive: bool,
              is_main: bool,
              is_unsorted_on: bool,
              name: String,
              sort: Integer
            }

          class Pipeline < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded?

            def _embedded=: (
              Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded
            ) -> Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader account_id: Integer?

            def account_id=: (Integer) -> Integer

            attr_reader is_archive: bool?

            def is_archive=: (bool) -> bool

            attr_reader is_main: bool?

            def is_main=: (bool) -> bool

            attr_reader is_unsorted_on: bool?

            def is_unsorted_on=: (bool) -> bool

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader sort: Integer?

            def sort=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?_embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded,
              ?_links: top,
              ?account_id: Integer,
              ?is_archive: bool,
              ?is_main: bool,
              ?is_unsorted_on: bool,
              ?name: String,
              ?sort: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              _embedded: Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded,
              _links: top,
              account_id: Integer,
              is_archive: bool,
              is_main: bool,
              is_unsorted_on: bool,
              name: String,
              sort: Integer
            }

            type embedded =
              {
                statuses: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]
              }

            class Embedded < Amocrm::Internal::Type::BaseModel
              attr_reader statuses: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]?

              def statuses=: (
                ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]
              ) -> ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]

              def initialize: (
                ?statuses: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]
              ) -> void

              def to_hash: -> {
                statuses: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status]
              }

              type status =
                {
                  id: Integer,
                  account_id: Integer,
                  color: String,
                  descriptions: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status::Description]?,
                  is_editable: bool,
                  name: String,
                  pipeline_id: Integer,
                  sort: Integer,
                  type: Integer
                }

              class Status < Amocrm::Internal::Type::BaseModel
                attr_reader id: Integer?

                def id=: (Integer) -> Integer

                attr_reader account_id: Integer?

                def account_id=: (Integer) -> Integer

                attr_reader color: String?

                def color=: (String) -> String

                attr_accessor descriptions: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status::Description]?

                attr_reader is_editable: bool?

                def is_editable=: (bool) -> bool

                attr_reader name: String?

                def name=: (String) -> String

                attr_reader pipeline_id: Integer?

                def pipeline_id=: (Integer) -> Integer

                attr_reader sort: Integer?

                def sort=: (Integer) -> Integer

                attr_reader type: Integer?

                def type=: (Integer) -> Integer

                def initialize: (
                  ?id: Integer,
                  ?account_id: Integer,
                  ?color: String,
                  ?descriptions: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status::Description]?,
                  ?is_editable: bool,
                  ?name: String,
                  ?pipeline_id: Integer,
                  ?sort: Integer,
                  ?type: Integer
                ) -> void

                def to_hash: -> {
                  id: Integer,
                  account_id: Integer,
                  color: String,
                  descriptions: ::Array[Amocrm::Models::V4PipelinesListResponse::PipelineListResponse::Embedded::Pipeline::Embedded::Status::Description]?,
                  is_editable: bool,
                  name: String,
                  pipeline_id: Integer,
                  sort: Integer,
                  type: Integer
                }

                type description =
                  {
                    id: Integer,
                    account_id: Integer,
                    created_at: Integer,
                    created_by: Integer,
                    description: String,
                    level: String,
                    pipeline_id: Integer,
                    status_id: Integer,
                    updated_at: Integer,
                    updated_by: Integer
                  }

                class Description < Amocrm::Internal::Type::BaseModel
                  attr_reader id: Integer?

                  def id=: (Integer) -> Integer

                  attr_reader account_id: Integer?

                  def account_id=: (Integer) -> Integer

                  attr_reader created_at: Integer?

                  def created_at=: (Integer) -> Integer

                  attr_reader created_by: Integer?

                  def created_by=: (Integer) -> Integer

                  attr_reader description: String?

                  def description=: (String) -> String

                  attr_reader level: String?

                  def level=: (String) -> String

                  attr_reader pipeline_id: Integer?

                  def pipeline_id=: (Integer) -> Integer

                  attr_reader status_id: Integer?

                  def status_id=: (Integer) -> Integer

                  attr_reader updated_at: Integer?

                  def updated_at=: (Integer) -> Integer

                  attr_reader updated_by: Integer?

                  def updated_by=: (Integer) -> Integer

                  def initialize: (
                    ?id: Integer,
                    ?account_id: Integer,
                    ?created_at: Integer,
                    ?created_by: Integer,
                    ?description: String,
                    ?level: String,
                    ?pipeline_id: Integer,
                    ?status_id: Integer,
                    ?updated_at: Integer,
                    ?updated_by: Integer
                  ) -> void

                  def to_hash: -> {
                    id: Integer,
                    account_id: Integer,
                    created_at: Integer,
                    created_by: Integer,
                    description: String,
                    level: String,
                    pipeline_id: Integer,
                    status_id: Integer,
                    updated_at: Integer,
                    updated_by: Integer
                  }
                end
              end
            end
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::v4_pipelines_list_response]
    end
  end
end
