module Amocrm
  module Models
    type v4_pipeline_statuses_create_response =
      Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse
      | Amocrm::Models::V4PipelineStatusesCreateResponse::Problem

    module V4PipelineStatusesCreateResponse
      extend Amocrm::Internal::Type::Union

      type status_create_response =
        {
          _embedded: Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded,
          _links: top
        }

      class StatusCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader _embedded: Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded?

        def _embedded=: (
          Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded
        ) -> Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded

        attr_reader _links: top?

        def _links=: (top) -> top

        def initialize: (
          ?_embedded: Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded,
          ?_links: top
        ) -> void

        def to_hash: -> {
          _embedded: Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded,
          _links: top
        }

        type embedded =
          {
            statuses: ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]
          }

        class Embedded < Amocrm::Internal::Type::BaseModel
          attr_reader statuses: ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]?

          def statuses=: (
            ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]
          ) -> ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]

          def initialize: (
            ?statuses: ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]
          ) -> void

          def to_hash: -> {
            statuses: ::Array[Amocrm::Models::V4PipelineStatusesCreateResponse::StatusCreateResponse::Embedded::Status]
          }

          type status = { id: Integer, _links: top, request_id: String }

          class Status < Amocrm::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _links: top?

            def _links=: (top) -> top

            attr_reader request_id: String?

            def request_id=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?_links: top,
              ?request_id: String
            ) -> void

            def to_hash: -> { id: Integer, _links: top, request_id: String }
          end
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::v4_pipeline_statuses_create_response]
    end
  end
end
