module Amocrm
  module Models
    type v4_pipeline_statuses_get_by_id_response =
      Amocrm::Models::V4PipelineStatusesGetByIDResponse::Status
      | Amocrm::Models::V4PipelineStatusesGetByIDResponse::Problem

    module V4PipelineStatusesGetByIDResponse
      extend Amocrm::Internal::Type::Union

      type status =
        {
          id: Integer,
          account_id: Integer,
          color: String,
          descriptions: ::Array[Amocrm::Models::V4PipelineStatusesGetByIDResponse::Status::Description]?,
          is_editable: bool,
          name: String,
          pipeline_id: Integer,
          sort: Integer,
          type: Integer
        }

      class Status < Amocrm::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader account_id: Integer?

        def account_id=: (Integer) -> Integer

        attr_reader color: String?

        def color=: (String) -> String

        attr_accessor descriptions: ::Array[Amocrm::Models::V4PipelineStatusesGetByIDResponse::Status::Description]?

        attr_reader is_editable: bool?

        def is_editable=: (bool) -> bool

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader pipeline_id: Integer?

        def pipeline_id=: (Integer) -> Integer

        attr_reader sort: Integer?

        def sort=: (Integer) -> Integer

        attr_reader type: Integer?

        def type=: (Integer) -> Integer

        def initialize: (
          ?id: Integer,
          ?account_id: Integer,
          ?color: String,
          ?descriptions: ::Array[Amocrm::Models::V4PipelineStatusesGetByIDResponse::Status::Description]?,
          ?is_editable: bool,
          ?name: String,
          ?pipeline_id: Integer,
          ?sort: Integer,
          ?type: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          account_id: Integer,
          color: String,
          descriptions: ::Array[Amocrm::Models::V4PipelineStatusesGetByIDResponse::Status::Description]?,
          is_editable: bool,
          name: String,
          pipeline_id: Integer,
          sort: Integer,
          type: Integer
        }

        type description =
          {
            id: Integer,
            account_id: Integer,
            created_at: Integer,
            created_by: Integer,
            description: String,
            level: String,
            pipeline_id: Integer,
            status_id: Integer,
            updated_at: Integer,
            updated_by: Integer
          }

        class Description < Amocrm::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader account_id: Integer?

          def account_id=: (Integer) -> Integer

          attr_reader created_at: Integer?

          def created_at=: (Integer) -> Integer

          attr_reader created_by: Integer?

          def created_by=: (Integer) -> Integer

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader level: String?

          def level=: (String) -> String

          attr_reader pipeline_id: Integer?

          def pipeline_id=: (Integer) -> Integer

          attr_reader status_id: Integer?

          def status_id=: (Integer) -> Integer

          attr_reader updated_at: Integer?

          def updated_at=: (Integer) -> Integer

          attr_reader updated_by: Integer?

          def updated_by=: (Integer) -> Integer

          def initialize: (
            ?id: Integer,
            ?account_id: Integer,
            ?created_at: Integer,
            ?created_by: Integer,
            ?description: String,
            ?level: String,
            ?pipeline_id: Integer,
            ?status_id: Integer,
            ?updated_at: Integer,
            ?updated_by: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            account_id: Integer,
            created_at: Integer,
            created_by: Integer,
            description: String,
            level: String,
            pipeline_id: Integer,
            status_id: Integer,
            updated_at: Integer,
            updated_by: Integer
          }
        end
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::v4_pipeline_statuses_get_by_id_response]
    end
  end
end
