module Amocrm
  module Models
    type v4_roles_create_params =
      { body: ::Array[Amocrm::V4RolesCreateParams::Body] }
      & Amocrm::Internal::Type::request_parameters

    class V4RolesCreateParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor body: ::Array[Amocrm::V4RolesCreateParams::Body]

      def initialize: (
        body: ::Array[Amocrm::V4RolesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        body: ::Array[Amocrm::V4RolesCreateParams::Body],
        request_options: Amocrm::RequestOptions
      }

      type body =
        {
          name: String,
          request_id: String,
          rights: Amocrm::V4RolesCreateParams::Body::Rights
        }

      class Body < Amocrm::Internal::Type::BaseModel
        attr_accessor name: String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        attr_reader rights: Amocrm::V4RolesCreateParams::Body::Rights?

        def rights=: (
          Amocrm::V4RolesCreateParams::Body::Rights
        ) -> Amocrm::V4RolesCreateParams::Body::Rights

        def initialize: (
          name: String,
          ?request_id: String,
          ?rights: Amocrm::V4RolesCreateParams::Body::Rights
        ) -> void

        def to_hash: -> {
          name: String,
          request_id: String,
          rights: Amocrm::V4RolesCreateParams::Body::Rights
        }

        type rights =
          {
            catalog_access: bool,
            companies: top,
            contacts: top,
            group_id: Integer?,
            is_active: bool,
            is_admin: bool,
            is_free: bool,
            leads: top,
            mail_access: bool,
            role_id: Integer?,
            status_rights: ::Array[Amocrm::V4RolesCreateParams::Body::Rights::StatusRight]?,
            tasks: top
          }

        class Rights < Amocrm::Internal::Type::BaseModel
          attr_reader catalog_access: bool?

          def catalog_access=: (bool) -> bool

          attr_reader companies: top?

          def companies=: (top) -> top

          attr_reader contacts: top?

          def contacts=: (top) -> top

          attr_accessor group_id: Integer?

          attr_reader is_active: bool?

          def is_active=: (bool) -> bool

          attr_reader is_admin: bool?

          def is_admin=: (bool) -> bool

          attr_reader is_free: bool?

          def is_free=: (bool) -> bool

          attr_reader leads: top?

          def leads=: (top) -> top

          attr_reader mail_access: bool?

          def mail_access=: (bool) -> bool

          attr_accessor role_id: Integer?

          attr_accessor status_rights: ::Array[Amocrm::V4RolesCreateParams::Body::Rights::StatusRight]?

          attr_reader tasks: top?

          def tasks=: (top) -> top

          def initialize: (
            ?catalog_access: bool,
            ?companies: top,
            ?contacts: top,
            ?group_id: Integer?,
            ?is_active: bool,
            ?is_admin: bool,
            ?is_free: bool,
            ?leads: top,
            ?mail_access: bool,
            ?role_id: Integer?,
            ?status_rights: ::Array[Amocrm::V4RolesCreateParams::Body::Rights::StatusRight]?,
            ?tasks: top
          ) -> void

          def to_hash: -> {
            catalog_access: bool,
            companies: top,
            contacts: top,
            group_id: Integer?,
            is_active: bool,
            is_admin: bool,
            is_free: bool,
            leads: top,
            mail_access: bool,
            role_id: Integer?,
            status_rights: ::Array[Amocrm::V4RolesCreateParams::Body::Rights::StatusRight]?,
            tasks: top
          }

          type status_right =
            {
              entity_type: String,
              pipeline_id: Integer,
              rights: top,
              status_id: Integer
            }

          class StatusRight < Amocrm::Internal::Type::BaseModel
            attr_reader entity_type: String?

            def entity_type=: (String) -> String

            attr_reader pipeline_id: Integer?

            def pipeline_id=: (Integer) -> Integer

            attr_reader rights: top?

            def rights=: (top) -> top

            attr_reader status_id: Integer?

            def status_id=: (Integer) -> Integer

            def initialize: (
              ?entity_type: String,
              ?pipeline_id: Integer,
              ?rights: top,
              ?status_id: Integer
            ) -> void

            def to_hash: -> {
              entity_type: String,
              pipeline_id: Integer,
              rights: top,
              status_id: Integer
            }
          end
        end
      end
    end
  end
end
