module Amocrm
  module Models
    type v4_short_links_create_response =
      Amocrm::Models::V4ShortLinksCreateResponse::ShortLinkCreateResponse
      | Amocrm::Models::V4ShortLinksCreateResponse::Problem

    module V4ShortLinksCreateResponse
      extend Amocrm::Internal::Type::Union

      type short_link_create_response = { short_link: String }

      class ShortLinkCreateResponse < Amocrm::Internal::Type::BaseModel
        attr_reader short_link: String?

        def short_link=: (String) -> String

        def initialize: (?short_link: String) -> void

        def to_hash: -> { short_link: String }
      end

      type problem =
        { detail: String, status: Integer, title: String, type: String }

      class Problem < Amocrm::Internal::Type::BaseModel
        attr_reader detail: String?

        def detail=: (String) -> String

        attr_reader status: Integer?

        def status=: (Integer) -> Integer

        attr_reader title: String?

        def title=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?detail: String,
          ?status: Integer,
          ?title: String,
          ?type: String
        ) -> void

        def to_hash: -> {
          detail: String,
          status: Integer,
          title: String,
          type: String
        }
      end

      def self?.variants: -> ::Array[Amocrm::Models::v4_short_links_create_response]
    end
  end
end
