module Amocrm
  module Models
    type webhook_unsubscribe_params =
      { destination: String } & Amocrm::Internal::Type::request_parameters

    class WebhookUnsubscribeParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor destination: String

      def initialize: (
        destination: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        destination: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
