module Amocrm
  module Models
    type website_button_connect_online_chat_params =
      { source_id: Integer } & Amocrm::Internal::Type::request_parameters

    class WebsiteButtonConnectOnlineChatParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor source_id: Integer

      def initialize: (
        source_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        source_id: Integer,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
