module Amocrm
  module Models
    type widget_get_by_code_params =
      { widget_code: String } & Amocrm::Internal::Type::request_parameters

    class WidgetGetByCodeParams < Amocrm::Internal::Type::BaseModel
      extend Amocrm::Internal::Type::RequestParameters::Converter
      include Amocrm::Internal::Type::RequestParameters

      attr_accessor widget_code: String

      def initialize: (
        widget_code: String,
        ?request_options: Amocrm::request_opts
      ) -> void

      def to_hash: -> {
        widget_code: String,
        request_options: Amocrm::RequestOptions
      }
    end
  end
end
