module Amocrm
  class APIAccountGetParams = Amocrm::Models::APIAccountGetParams

  class APICallsCreateParams = Amocrm::Models::APICallsCreateParams

  class APICatalogElementsCreateParams = Amocrm::Models::APICatalogElementsCreateParams

  class APICatalogElementsGetByIDParams = Amocrm::Models::APICatalogElementsGetByIDParams

  class APICatalogElementsListParams = Amocrm::Models::APICatalogElementsListParams

  class APICatalogElementsUpdateByIDParams = Amocrm::Models::APICatalogElementsUpdateByIDParams

  class APICatalogElementsUpdateParams = Amocrm::Models::APICatalogElementsUpdateParams

  class APICatalogsCreateParams = Amocrm::Models::APICatalogsCreateParams

  class APICatalogsGetByIDParams = Amocrm::Models::APICatalogsGetByIDParams

  class APICatalogsListParams = Amocrm::Models::APICatalogsListParams

  class APICatalogsUpdateByIDParams = Amocrm::Models::APICatalogsUpdateByIDParams

  class APICatalogsUpdateParams = Amocrm::Models::APICatalogsUpdateParams

  class APICompaniesCreateParams = Amocrm::Models::APICompaniesCreateParams

  class APICompaniesGetByIDParams = Amocrm::Models::APICompaniesGetByIDParams

  class APICompaniesListParams = Amocrm::Models::APICompaniesListParams

  class APICompaniesUpdateByIDParams = Amocrm::Models::APICompaniesUpdateByIDParams

  class APICompaniesUpdateParams = Amocrm::Models::APICompaniesUpdateParams

  class APIContactChatsLinkParams = Amocrm::Models::APIContactChatsLinkParams

  class APIContactChatsListParams = Amocrm::Models::APIContactChatsListParams

  class APIContactsCreateParams = Amocrm::Models::APIContactsCreateParams

  class APIContactsGetByIDParams = Amocrm::Models::APIContactsGetByIDParams

  class APIContactsListParams = Amocrm::Models::APIContactsListParams

  class APIContactsUpdateByIDParams = Amocrm::Models::APIContactsUpdateByIDParams

  class APIContactsUpdateParams = Amocrm::Models::APIContactsUpdateParams

  class APICustomerBonusPointsChangeParams = Amocrm::Models::APICustomerBonusPointsChangeParams

  class APICustomersCreateParams = Amocrm::Models::APICustomersCreateParams

  class APICustomerSegmentsCreateParams = Amocrm::Models::APICustomerSegmentsCreateParams

  class APICustomerSegmentsDeleteByIDParams = Amocrm::Models::APICustomerSegmentsDeleteByIDParams

  class APICustomerSegmentsGetByIDParams = Amocrm::Models::APICustomerSegmentsGetByIDParams

  class APICustomerSegmentsListParams = Amocrm::Models::APICustomerSegmentsListParams

  class APICustomerSegmentsUpdateByIDParams = Amocrm::Models::APICustomerSegmentsUpdateByIDParams

  class APICustomersGetByIDParams = Amocrm::Models::APICustomersGetByIDParams

  class APICustomersListParams = Amocrm::Models::APICustomersListParams

  class APICustomersModeSetModeParams = Amocrm::Models::APICustomersModeSetModeParams

  class APICustomerStatusesCreateParams = Amocrm::Models::APICustomerStatusesCreateParams

  class APICustomerStatusesDeleteByIDParams = Amocrm::Models::APICustomerStatusesDeleteByIDParams

  class APICustomerStatusesGetByIDParams = Amocrm::Models::APICustomerStatusesGetByIDParams

  class APICustomerStatusesListParams = Amocrm::Models::APICustomerStatusesListParams

  class APICustomerStatusesUpdateByIDParams = Amocrm::Models::APICustomerStatusesUpdateByIDParams

  class APICustomersUpdateByIDParams = Amocrm::Models::APICustomersUpdateByIDParams

  class APICustomersUpdateParams = Amocrm::Models::APICustomersUpdateParams

  class APICustomerTransactionsCreateParams = Amocrm::Models::APICustomerTransactionsCreateParams

  class APICustomerTransactionsDeleteByIDParams = Amocrm::Models::APICustomerTransactionsDeleteByIDParams

  class APICustomerTransactionsListByCustomerParams = Amocrm::Models::APICustomerTransactionsListByCustomerParams

  class APICustomerTransactionsListParams = Amocrm::Models::APICustomerTransactionsListParams

  class APICustomFieldGroupsCreateParams = Amocrm::Models::APICustomFieldGroupsCreateParams

  class APICustomFieldGroupsDeleteByIDParams = Amocrm::Models::APICustomFieldGroupsDeleteByIDParams

  class APICustomFieldGroupsGetByIDParams = Amocrm::Models::APICustomFieldGroupsGetByIDParams

  class APICustomFieldGroupsListParams = Amocrm::Models::APICustomFieldGroupsListParams

  class APICustomFieldGroupsUpdateByIDParams = Amocrm::Models::APICustomFieldGroupsUpdateByIDParams

  class APICustomFieldsCreateParams = Amocrm::Models::APICustomFieldsCreateParams

  class APICustomFieldsDeleteByIDParams = Amocrm::Models::APICustomFieldsDeleteByIDParams

  class APICustomFieldsGetByIDParams = Amocrm::Models::APICustomFieldsGetByIDParams

  class APICustomFieldsListParams = Amocrm::Models::APICustomFieldsListParams

  class APICustomFieldsUpdateByIDParams = Amocrm::Models::APICustomFieldsUpdateByIDParams

  class APICustomFieldsUpdateParams = Amocrm::Models::APICustomFieldsUpdateParams

  class APIEntityFollowersAddParams = Amocrm::Models::APIEntityFollowersAddParams

  class APIEntityFollowersListParams = Amocrm::Models::APIEntityFollowersListParams

  class APIEntityFollowersRemoveParams = Amocrm::Models::APIEntityFollowersRemoveParams

  class APIEntityLinksLinkByEntityParams = Amocrm::Models::APIEntityLinksLinkByEntityParams

  class APIEntityLinksLinkParams = Amocrm::Models::APIEntityLinksLinkParams

  class APIEntityLinksListByEntityParams = Amocrm::Models::APIEntityLinksListByEntityParams

  class APIEntityLinksListParams = Amocrm::Models::APIEntityLinksListParams

  class APIEntityLinksUnlinkByEntityParams = Amocrm::Models::APIEntityLinksUnlinkByEntityParams

  class APIEntityLinksUnlinkParams = Amocrm::Models::APIEntityLinksUnlinkParams

  class APIEntityNotesByParentCreateByParentParams = Amocrm::Models::APIEntityNotesByParentCreateByParentParams

  class APIEntityNotesByParentGetByParentIDParams = Amocrm::Models::APIEntityNotesByParentGetByParentIDParams

  class APIEntityNotesByParentListByParentParams = Amocrm::Models::APIEntityNotesByParentListByParentParams

  class APIEntityNotesByParentUpdateByParentIDParams = Amocrm::Models::APIEntityNotesByParentUpdateByParentIDParams

  class APIEntityNotesByParentUpdateByParentParams = Amocrm::Models::APIEntityNotesByParentUpdateByParentParams

  class APIEntityNotesCreateParams = Amocrm::Models::APIEntityNotesCreateParams

  class APIEntityNotesGetByIDParams = Amocrm::Models::APIEntityNotesGetByIDParams

  class APIEntityNotesListParams = Amocrm::Models::APIEntityNotesListParams

  class APIEntityNotesPinParams = Amocrm::Models::APIEntityNotesPinParams

  class APIEntityNotesUnpinParams = Amocrm::Models::APIEntityNotesUnpinParams

  class APIEntityNotesUpdateByIDParams = Amocrm::Models::APIEntityNotesUpdateByIDParams

  class APIEntityNotesUpdateParams = Amocrm::Models::APIEntityNotesUpdateParams

  class APIEventsGetByIDParams = Amocrm::Models::APIEventsGetByIDParams

  class APIEventsListParams = Amocrm::Models::APIEventsListParams

  class APIEventsListTypesParams = Amocrm::Models::APIEventsListTypesParams

  class APILeadsCreateComplexParams = Amocrm::Models::APILeadsCreateComplexParams

  class APILeadsCreateParams = Amocrm::Models::APILeadsCreateParams

  class APILeadsGetByIDParams = Amocrm::Models::APILeadsGetByIDParams

  class APILeadsListParams = Amocrm::Models::APILeadsListParams

  class APILeadsUpdateByIDParams = Amocrm::Models::APILeadsUpdateByIDParams

  class APILeadsUpdateParams = Amocrm::Models::APILeadsUpdateParams

  class APIPipelinesCreateParams = Amocrm::Models::APIPipelinesCreateParams

  class APIPipelinesDeleteByIDParams = Amocrm::Models::APIPipelinesDeleteByIDParams

  class APIPipelinesGetByIDParams = Amocrm::Models::APIPipelinesGetByIDParams

  class APIPipelinesListParams = Amocrm::Models::APIPipelinesListParams

  class APIPipelineStatusesCreateParams = Amocrm::Models::APIPipelineStatusesCreateParams

  class APIPipelineStatusesDeleteByIDParams = Amocrm::Models::APIPipelineStatusesDeleteByIDParams

  class APIPipelineStatusesGetByIDParams = Amocrm::Models::APIPipelineStatusesGetByIDParams

  class APIPipelineStatusesListParams = Amocrm::Models::APIPipelineStatusesListParams

  class APIPipelineStatusesUpdateByIDParams = Amocrm::Models::APIPipelineStatusesUpdateByIDParams

  class APIPipelineStatusesUpdateParams = Amocrm::Models::APIPipelineStatusesUpdateParams

  class APIPipelinesUpdateByIDParams = Amocrm::Models::APIPipelinesUpdateByIDParams

  class APIPipelinesUpdateParams = Amocrm::Models::APIPipelinesUpdateParams

  class APIRolesCreateParams = Amocrm::Models::APIRolesCreateParams

  class APIRolesDeleteByIDParams = Amocrm::Models::APIRolesDeleteByIDParams

  class APIRolesGetByIDParams = Amocrm::Models::APIRolesGetByIDParams

  class APIRolesListParams = Amocrm::Models::APIRolesListParams

  class APIRolesUpdateByIDParams = Amocrm::Models::APIRolesUpdateByIDParams

  class APISalesbotRunParams = Amocrm::Models::APISalesbotRunParams

  class APIShortLinksCreateParams = Amocrm::Models::APIShortLinksCreateParams

  class APISourcesCreateParams = Amocrm::Models::APISourcesCreateParams

  class APISourcesDeleteByIDParams = Amocrm::Models::APISourcesDeleteByIDParams

  class APISourcesDeleteParams = Amocrm::Models::APISourcesDeleteParams

  class APISourcesGetByIDParams = Amocrm::Models::APISourcesGetByIDParams

  class APISourcesListParams = Amocrm::Models::APISourcesListParams

  class APISourcesUpdateByIDParams = Amocrm::Models::APISourcesUpdateByIDParams

  class APISourcesUpdateParams = Amocrm::Models::APISourcesUpdateParams

  class APITagsCreateParams = Amocrm::Models::APITagsCreateParams

  class APITagsListParams = Amocrm::Models::APITagsListParams

  class APITalksCloseParams = Amocrm::Models::APITalksCloseParams

  class APITalksGetByIDParams = Amocrm::Models::APITalksGetByIDParams

  class APITasksCreateParams = Amocrm::Models::APITasksCreateParams

  class APITasksGetByIDParams = Amocrm::Models::APITasksGetByIDParams

  class APITasksListParams = Amocrm::Models::APITasksListParams

  class APITasksUpdateByIDParams = Amocrm::Models::APITasksUpdateByIDParams

  class APITasksUpdateParams = Amocrm::Models::APITasksUpdateParams

  class APIUnsortedLeadsAcceptParams = Amocrm::Models::APIUnsortedLeadsAcceptParams

  class APIUnsortedLeadsCreateFormsParams = Amocrm::Models::APIUnsortedLeadsCreateFormsParams

  class APIUnsortedLeadsDeclineParams = Amocrm::Models::APIUnsortedLeadsDeclineParams

  class APIUsersCreateParams = Amocrm::Models::APIUsersCreateParams

  class APIUsersGetByIDParams = Amocrm::Models::APIUsersGetByIDParams

  class APIUsersListParams = Amocrm::Models::APIUsersListParams

  class APIWebhooksListParams = Amocrm::Models::APIWebhooksListParams

  class APIWebhooksSubscribeParams = Amocrm::Models::APIWebhooksSubscribeParams

  class APIWebhooksUnsubscribeParams = Amocrm::Models::APIWebhooksUnsubscribeParams

  class APIWebsiteButtonsConnectOnlineChatParams = Amocrm::Models::APIWebsiteButtonsConnectOnlineChatParams

  class APIWebsiteButtonsCreateParams = Amocrm::Models::APIWebsiteButtonsCreateParams

  class APIWebsiteButtonsGetBySourceIDParams = Amocrm::Models::APIWebsiteButtonsGetBySourceIDParams

  class APIWebsiteButtonsListParams = Amocrm::Models::APIWebsiteButtonsListParams

  class APIWebsiteButtonsUpdateParams = Amocrm::Models::APIWebsiteButtonsUpdateParams

  class APIWidgetBotContinueContinueParams = Amocrm::Models::APIWidgetBotContinueContinueParams

  class APIWidgetsGetByCodeParams = Amocrm::Models::APIWidgetsGetByCodeParams

  class APIWidgetsInstallParams = Amocrm::Models::APIWidgetsInstallParams

  class APIWidgetsListParams = Amocrm::Models::APIWidgetsListParams

  class APIWidgetsUninstallParams = Amocrm::Models::APIWidgetsUninstallParams
end
