module Amocrm
  class AccountGetParams = Amocrm::Models::AccountGetParams

  class CallCreateParams = Amocrm::Models::CallCreateParams

  class CatalogCreateParams = Amocrm::Models::CatalogCreateParams

  class CatalogElementCreateParams = Amocrm::Models::CatalogElementCreateParams

  class CatalogElementGetByIDParams = Amocrm::Models::CatalogElementGetByIDParams

  class CatalogElementListParams = Amocrm::Models::CatalogElementListParams

  class CatalogElementUpdateByIDParams = Amocrm::Models::CatalogElementUpdateByIDParams

  class CatalogElementUpdateParams = Amocrm::Models::CatalogElementUpdateParams

  class CatalogGetByIDParams = Amocrm::Models::CatalogGetByIDParams

  class CatalogListParams = Amocrm::Models::CatalogListParams

  class CatalogUpdateByIDParams = Amocrm::Models::CatalogUpdateByIDParams

  class CatalogUpdateParams = Amocrm::Models::CatalogUpdateParams

  class CompanyCreateParams = Amocrm::Models::CompanyCreateParams

  class CompanyGetByIDParams = Amocrm::Models::CompanyGetByIDParams

  class CompanyListParams = Amocrm::Models::CompanyListParams

  class CompanyUpdateByIDParams = Amocrm::Models::CompanyUpdateByIDParams

  class CompanyUpdateParams = Amocrm::Models::CompanyUpdateParams

  class ContactChatLinkParams = Amocrm::Models::ContactChatLinkParams

  class ContactChatListParams = Amocrm::Models::ContactChatListParams

  class ContactCreateParams = Amocrm::Models::ContactCreateParams

  class ContactGetByIDParams = Amocrm::Models::ContactGetByIDParams

  class ContactListParams = Amocrm::Models::ContactListParams

  class ContactUpdateByIDParams = Amocrm::Models::ContactUpdateByIDParams

  class ContactUpdateParams = Amocrm::Models::ContactUpdateParams

  class CustomerBonusPointChangeParams = Amocrm::Models::CustomerBonusPointChangeParams

  class CustomerCreateParams = Amocrm::Models::CustomerCreateParams

  class CustomerGetByIDParams = Amocrm::Models::CustomerGetByIDParams

  class CustomerListParams = Amocrm::Models::CustomerListParams

  class CustomerSegmentCreateParams = Amocrm::Models::CustomerSegmentCreateParams

  class CustomerSegmentDeleteByIDParams = Amocrm::Models::CustomerSegmentDeleteByIDParams

  class CustomerSegmentGetByIDParams = Amocrm::Models::CustomerSegmentGetByIDParams

  class CustomerSegmentListParams = Amocrm::Models::CustomerSegmentListParams

  class CustomerSegmentUpdateByIDParams = Amocrm::Models::CustomerSegmentUpdateByIDParams

  class CustomersModeSetModeParams = Amocrm::Models::CustomersModeSetModeParams

  class CustomerStatusCreateParams = Amocrm::Models::CustomerStatusCreateParams

  class CustomerStatusDeleteByIDParams = Amocrm::Models::CustomerStatusDeleteByIDParams

  class CustomerStatusGetByIDParams = Amocrm::Models::CustomerStatusGetByIDParams

  class CustomerStatusListParams = Amocrm::Models::CustomerStatusListParams

  class CustomerStatusUpdateByIDParams = Amocrm::Models::CustomerStatusUpdateByIDParams

  class CustomerTransactionCreateParams = Amocrm::Models::CustomerTransactionCreateParams

  class CustomerTransactionDeleteByIDParams = Amocrm::Models::CustomerTransactionDeleteByIDParams

  class CustomerTransactionListByCustomerParams = Amocrm::Models::CustomerTransactionListByCustomerParams

  class CustomerTransactionListParams = Amocrm::Models::CustomerTransactionListParams

  class CustomerUpdateByIDParams = Amocrm::Models::CustomerUpdateByIDParams

  class CustomerUpdateParams = Amocrm::Models::CustomerUpdateParams

  class CustomFieldCreateParams = Amocrm::Models::CustomFieldCreateParams

  class CustomFieldDeleteByIDParams = Amocrm::Models::CustomFieldDeleteByIDParams

  class CustomFieldGetByIDParams = Amocrm::Models::CustomFieldGetByIDParams

  class CustomFieldGroupCreateParams = Amocrm::Models::CustomFieldGroupCreateParams

  class CustomFieldGroupDeleteByIDParams = Amocrm::Models::CustomFieldGroupDeleteByIDParams

  class CustomFieldGroupGetByIDParams = Amocrm::Models::CustomFieldGroupGetByIDParams

  class CustomFieldGroupListParams = Amocrm::Models::CustomFieldGroupListParams

  class CustomFieldGroupUpdateByIDParams = Amocrm::Models::CustomFieldGroupUpdateByIDParams

  class CustomFieldListParams = Amocrm::Models::CustomFieldListParams

  class CustomFieldUpdateByIDParams = Amocrm::Models::CustomFieldUpdateByIDParams

  class CustomFieldUpdateParams = Amocrm::Models::CustomFieldUpdateParams

  class EntityFollowerAddParams = Amocrm::Models::EntityFollowerAddParams

  class EntityFollowerListParams = Amocrm::Models::EntityFollowerListParams

  class EntityFollowerRemoveParams = Amocrm::Models::EntityFollowerRemoveParams

  class EntityLinkLinkByEntityParams = Amocrm::Models::EntityLinkLinkByEntityParams

  class EntityLinkLinkParams = Amocrm::Models::EntityLinkLinkParams

  class EntityLinkListByEntityParams = Amocrm::Models::EntityLinkListByEntityParams

  class EntityLinkListParams = Amocrm::Models::EntityLinkListParams

  class EntityLinkUnlinkByEntityParams = Amocrm::Models::EntityLinkUnlinkByEntityParams

  class EntityLinkUnlinkParams = Amocrm::Models::EntityLinkUnlinkParams

  class EntityNoteCreateParams = Amocrm::Models::EntityNoteCreateParams

  class EntityNoteGetByIDParams = Amocrm::Models::EntityNoteGetByIDParams

  class EntityNoteListParams = Amocrm::Models::EntityNoteListParams

  class EntityNotePinParams = Amocrm::Models::EntityNotePinParams

  class EntityNotesByParentCreateByParentParams = Amocrm::Models::EntityNotesByParentCreateByParentParams

  class EntityNotesByParentGetByParentIDParams = Amocrm::Models::EntityNotesByParentGetByParentIDParams

  class EntityNotesByParentListByParentParams = Amocrm::Models::EntityNotesByParentListByParentParams

  class EntityNotesByParentUpdateByParentIDParams = Amocrm::Models::EntityNotesByParentUpdateByParentIDParams

  class EntityNotesByParentUpdateByParentParams = Amocrm::Models::EntityNotesByParentUpdateByParentParams

  class EntityNoteUnpinParams = Amocrm::Models::EntityNoteUnpinParams

  class EntityNoteUpdateByIDParams = Amocrm::Models::EntityNoteUpdateByIDParams

  class EntityNoteUpdateParams = Amocrm::Models::EntityNoteUpdateParams

  class EventGetByIDParams = Amocrm::Models::EventGetByIDParams

  class EventListParams = Amocrm::Models::EventListParams

  class EventListTypesParams = Amocrm::Models::EventListTypesParams

  class LeadCreateComplexParams = Amocrm::Models::LeadCreateComplexParams

  class LeadCreateParams = Amocrm::Models::LeadCreateParams

  class LeadGetByIDParams = Amocrm::Models::LeadGetByIDParams

  class LeadListParams = Amocrm::Models::LeadListParams

  class LeadUpdateByIDParams = Amocrm::Models::LeadUpdateByIDParams

  class LeadUpdateParams = Amocrm::Models::LeadUpdateParams

  class PipelineCreateParams = Amocrm::Models::PipelineCreateParams

  class PipelineDeleteByIDParams = Amocrm::Models::PipelineDeleteByIDParams

  class PipelineGetByIDParams = Amocrm::Models::PipelineGetByIDParams

  class PipelineListParams = Amocrm::Models::PipelineListParams

  class PipelineStatusCreateParams = Amocrm::Models::PipelineStatusCreateParams

  class PipelineStatusDeleteByIDParams = Amocrm::Models::PipelineStatusDeleteByIDParams

  class PipelineStatusGetByIDParams = Amocrm::Models::PipelineStatusGetByIDParams

  class PipelineStatusListParams = Amocrm::Models::PipelineStatusListParams

  class PipelineStatusUpdateByIDParams = Amocrm::Models::PipelineStatusUpdateByIDParams

  class PipelineStatusUpdateParams = Amocrm::Models::PipelineStatusUpdateParams

  class PipelineUpdateByIDParams = Amocrm::Models::PipelineUpdateByIDParams

  class PipelineUpdateParams = Amocrm::Models::PipelineUpdateParams

  class RoleCreateParams = Amocrm::Models::RoleCreateParams

  class RoleDeleteByIDParams = Amocrm::Models::RoleDeleteByIDParams

  class RoleGetByIDParams = Amocrm::Models::RoleGetByIDParams

  class RoleListParams = Amocrm::Models::RoleListParams

  class RoleUpdateByIDParams = Amocrm::Models::RoleUpdateByIDParams

  class SalesbotRunParams = Amocrm::Models::SalesbotRunParams

  class ShortLinkCreateParams = Amocrm::Models::ShortLinkCreateParams

  class SourceCreateParams = Amocrm::Models::SourceCreateParams

  class SourceDeleteByIDParams = Amocrm::Models::SourceDeleteByIDParams

  class SourceDeleteParams = Amocrm::Models::SourceDeleteParams

  class SourceGetByIDParams = Amocrm::Models::SourceGetByIDParams

  class SourceListParams = Amocrm::Models::SourceListParams

  class SourceUpdateByIDParams = Amocrm::Models::SourceUpdateByIDParams

  class SourceUpdateParams = Amocrm::Models::SourceUpdateParams

  class TagCreateParams = Amocrm::Models::TagCreateParams

  class TagListParams = Amocrm::Models::TagListParams

  class TalkCloseParams = Amocrm::Models::TalkCloseParams

  class TalkGetByIDParams = Amocrm::Models::TalkGetByIDParams

  class TaskCreateParams = Amocrm::Models::TaskCreateParams

  class TaskGetByIDParams = Amocrm::Models::TaskGetByIDParams

  class TaskListParams = Amocrm::Models::TaskListParams

  class TaskUpdateByIDParams = Amocrm::Models::TaskUpdateByIDParams

  class TaskUpdateParams = Amocrm::Models::TaskUpdateParams

  class UnsortedLeadAcceptParams = Amocrm::Models::UnsortedLeadAcceptParams

  class UnsortedLeadCreateFormsParams = Amocrm::Models::UnsortedLeadCreateFormsParams

  class UnsortedLeadDeclineParams = Amocrm::Models::UnsortedLeadDeclineParams

  class UserCreateParams = Amocrm::Models::UserCreateParams

  class UserGetByIDParams = Amocrm::Models::UserGetByIDParams

  class UserListParams = Amocrm::Models::UserListParams

  class WebhookListParams = Amocrm::Models::WebhookListParams

  class WebhookSubscribeParams = Amocrm::Models::WebhookSubscribeParams

  class WebhookUnsubscribeParams = Amocrm::Models::WebhookUnsubscribeParams

  class WebsiteButtonConnectOnlineChatParams = Amocrm::Models::WebsiteButtonConnectOnlineChatParams

  class WebsiteButtonCreateParams = Amocrm::Models::WebsiteButtonCreateParams

  class WebsiteButtonGetBySourceIDParams = Amocrm::Models::WebsiteButtonGetBySourceIDParams

  class WebsiteButtonListParams = Amocrm::Models::WebsiteButtonListParams

  class WebsiteButtonUpdateParams = Amocrm::Models::WebsiteButtonUpdateParams

  class WidgetBotContinueContinueParams = Amocrm::Models::WidgetBotContinueContinueParams

  class WidgetGetByCodeParams = Amocrm::Models::WidgetGetByCodeParams

  class WidgetInstallParams = Amocrm::Models::WidgetInstallParams

  class WidgetListParams = Amocrm::Models::WidgetListParams

  class WidgetUninstallParams = Amocrm::Models::WidgetUninstallParams
end
