module Amocrm
  module Resources
    class API
      def account_get: (
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_account_get_response

      def calls_create: (
        body: ::Array[Amocrm::APICallsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_calls_create_response

      def catalog_elements_create: (
        Integer catalog_id,
        body: ::Array[Amocrm::APICatalogElementsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalog_elements_create_response

      def catalog_elements_get_by_id: (
        Integer id,
        catalog_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalog_elements_get_by_id_response

      def catalog_elements_list: (
        Integer catalog_id,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?query: Amocrm::Models::APICatalogElementsListParams::query,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalog_elements_list_response

      def catalog_elements_update: (
        Integer catalog_id,
        body: ::Array[Amocrm::APICatalogElementsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalog_elements_update_response

      def catalog_elements_update_by_id: (
        Integer id,
        catalog_id: Integer,
        ?custom_fields_values: ::Array[Amocrm::APICatalogElementsUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_id: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalog_elements_update_by_id_response

      def catalogs_create: (
        body: ::Array[Amocrm::APICatalogsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalogs_create_response

      def catalogs_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalogs_get_by_id_response

      def catalogs_list: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalogs_list_response

      def catalogs_update: (
        body: ::Array[Amocrm::APICatalogsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalogs_update_response

      def catalogs_update_by_id: (
        Integer id,
        ?can_add_elements: bool,
        ?can_link_multiple: bool,
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_catalogs_update_by_id_response

      def companies_create: (
        body: ::Array[Amocrm::APICompaniesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_companies_create_response

      def companies_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_companies_get_by_id_response

      def companies_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::APICompaniesListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_companies_list_response

      def companies_update: (
        body: ::Array[Amocrm::APICompaniesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_companies_update_response

      def companies_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::APICompaniesUpdateByIDParams::Embedded,
        ?created_at: Integer,
        ?created_by: Integer,
        ?custom_fields_values: ::Array[Amocrm::APICompaniesUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?responsible_user_id: Integer,
        ?tags_to_add: ::Array[Amocrm::APICompaniesUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::APICompaniesUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_companies_update_by_id_response

      def contact_chats_link: (
        body: ::Array[Amocrm::APIContactChatsLinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contact_chats_link_response

      def contact_chats_list: (
        ?filter: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contact_chats_list_response

      def contacts_create: (
        body: ::Array[Amocrm::APIContactsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contacts_create_response

      def contacts_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contacts_get_by_id_response

      def contacts_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::APIContactsListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contacts_list_response

      def contacts_update: (
        body: ::Array[Amocrm::APIContactsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contacts_update_response

      def contacts_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::APIContactsUpdateByIDParams::Embedded,
        ?created_at: Integer,
        ?created_by: Integer,
        ?custom_fields_values: ::Array[Amocrm::APIContactsUpdateByIDParams::CustomFieldsValue],
        ?first_name: String,
        ?last_name: String,
        ?name: String,
        ?responsible_user_id: Integer,
        ?tags_to_add: ::Array[Amocrm::APIContactsUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::APIContactsUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_contacts_update_by_id_response

      def custom_field_groups_create: (
        String entity_type,
        body: ::Array[Amocrm::APICustomFieldGroupsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_field_groups_create_response

      def custom_field_groups_delete_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_field_groups_delete_by_id_response

      def custom_field_groups_get_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_field_groups_get_by_id_response

      def custom_field_groups_list: (
        String entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_field_groups_list_response

      def custom_field_groups_update_by_id: (
        Integer id,
        entity_type: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_field_groups_update_by_id_response

      def custom_fields_create: (
        String entity_type,
        body: ::Array[Amocrm::APICustomFieldsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_create_response

      def custom_fields_delete_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_delete_by_id_response

      def custom_fields_get_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_get_by_id_response

      def custom_fields_list: (
        String entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_list_response

      def custom_fields_update: (
        String entity_type,
        body: ::Array[Amocrm::APICustomFieldsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_update_response

      def custom_fields_update_by_id: (
        Integer id,
        entity_type: String,
        ?code: String,
        ?enums: ::Array[top],
        ?group_id: Integer,
        ?is_deletable: bool,
        ?is_multiple: bool,
        ?is_required: bool,
        ?is_visible: bool,
        ?name: String,
        ?settings: top,
        ?sort: Integer,
        ?type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_custom_fields_update_by_id_response

      def customer_bonus_points_change: (
        Integer customer_id,
        earn: Integer,
        redeem: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_bonus_points_change_response

      def customer_segments_create: (
        body: ::Array[Amocrm::APICustomerSegmentsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_segments_create_response

      def customer_segments_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_segments_delete_by_id_response

      def customer_segments_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_segments_get_by_id_response

      def customer_segments_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_segments_list_response

      def customer_segments_update_by_id: (
        Integer id,
        ?color: String,
        ?custom_fields_values: ::Array[Amocrm::APICustomerSegmentsUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_segments_update_by_id_response

      def customer_statuses_create: (
        body: ::Array[Amocrm::APICustomerStatusesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_statuses_create_response

      def customer_statuses_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_statuses_delete_by_id_response

      def customer_statuses_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_statuses_get_by_id_response

      def customer_statuses_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_statuses_list_response

      def customer_statuses_update_by_id: (
        Integer id,
        ?color: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_statuses_update_by_id_response

      def customer_transactions_create: (
        Integer customer_id,
        body: ::Array[Amocrm::APICustomerTransactionsCreateParams::Body],
        ?accrue_bonus: bool,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_transactions_create_response

      def customer_transactions_delete_by_id: (
        Integer transaction_id,
        customer_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_transactions_delete_by_id_response

      def customer_transactions_list: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_transactions_list_response

      def customer_transactions_list_by_customer: (
        Integer customer_id,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customer_transactions_list_by_customer_response

      def customers_create: (
        body: ::Array[Amocrm::APICustomersCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_create_response

      def customers_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_get_by_id_response

      def customers_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::APICustomersListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_list_response

      def customers_mode_set_mode: (
        is_enabled: bool,
        mode: Amocrm::Models::APICustomersModeSetModeParams::mode,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_mode_set_mode_response

      def customers_update: (
        body: ::Array[Amocrm::APICustomersUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_update_response

      def customers_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::APICustomersUpdateByIDParams::Embedded,
        ?custom_fields_values: ::Array[Amocrm::APICustomersUpdateByIDParams::CustomFieldsValue],
        ?main_user_id: Integer,
        ?name: String,
        ?next_date: Integer,
        ?next_price: Integer,
        ?periodicity: Integer,
        ?responsible_user_id: Integer,
        ?status_id: Integer,
        ?tags_to_add: ::Array[Amocrm::APICustomersUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::APICustomersUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_customers_update_by_id_response

      def entity_followers_add: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityFollowersAddParams::entity_type,
        body: ::Array[Amocrm::APIEntityFollowersAddParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_followers_add_response

      def entity_followers_list: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityFollowersListParams::entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_followers_list_response

      def entity_followers_remove: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityFollowersRemoveParams::entity_type,
        body: ::Array[Amocrm::APIEntityFollowersRemoveParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_followers_remove_response

      def entity_links_link: (
        Amocrm::Models::APIEntityLinksLinkParams::entity_type entity_type,
        body: ::Array[Amocrm::APIEntityLinksLinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_link_response

      def entity_links_link_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityLinksLinkByEntityParams::entity_type,
        body: ::Array[Amocrm::APIEntityLinksLinkByEntityParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_link_by_entity_response

      def entity_links_list: (
        Amocrm::Models::APIEntityLinksListParams::entity_type entity_type,
        ?filter: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_list_response

      def entity_links_list_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityLinksListByEntityParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_list_by_entity_response

      def entity_links_unlink: (
        Amocrm::Models::APIEntityLinksUnlinkParams::entity_type entity_type,
        body: ::Array[Amocrm::APIEntityLinksUnlinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_unlink_response

      def entity_links_unlink_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityLinksUnlinkByEntityParams::entity_type,
        body: ::Array[Amocrm::APIEntityLinksUnlinkByEntityParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_links_unlink_by_entity_response

      def entity_notes_by_parent_create_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityNotesByParentCreateByParentParams::entity_type,
        body: ::Array[Amocrm::APIEntityNotesByParentCreateByParentParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_by_parent_create_by_parent_response

      def entity_notes_by_parent_get_by_parent_id: (
        Integer note_id,
        entity_type: Amocrm::Models::APIEntityNotesByParentGetByParentIDParams::entity_type,
        entity_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_by_parent_get_by_parent_id_response

      def entity_notes_by_parent_list_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityNotesByParentListByParentParams::entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_by_parent_list_by_parent_response

      def entity_notes_by_parent_update_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::APIEntityNotesByParentUpdateByParentParams::entity_type,
        body: ::Array[Amocrm::APIEntityNotesByParentUpdateByParentParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_by_parent_update_by_parent_response

      def entity_notes_by_parent_update_by_parent_id: (
        Integer note_id,
        entity_type: Amocrm::Models::APIEntityNotesByParentUpdateByParentIDParams::entity_type,
        ?body_entity_id: Integer,
        ?note_type: String,
        ?params: top,
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_by_parent_update_by_parent_id_response

      def entity_notes_create: (
        Amocrm::Models::APIEntityNotesCreateParams::entity_type entity_type,
        body: ::Array[Amocrm::APIEntityNotesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_create_response

      def entity_notes_get_by_id: (
        Integer id,
        entity_type: Amocrm::Models::APIEntityNotesGetByIDParams::entity_type,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_get_by_id_response

      def entity_notes_list: (
        Amocrm::Models::APIEntityNotesListParams::entity_type entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_list_response

      def entity_notes_pin: (
        Integer id,
        entity_type: Amocrm::Models::APIEntityNotesPinParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_pin_response

      def entity_notes_unpin: (
        Integer id,
        entity_type: Amocrm::Models::APIEntityNotesUnpinParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_unpin_response

      def entity_notes_update: (
        Amocrm::Models::APIEntityNotesUpdateParams::entity_type entity_type,
        body: ::Array[Amocrm::APIEntityNotesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_update_response

      def entity_notes_update_by_id: (
        Integer id,
        entity_type: Amocrm::Models::APIEntityNotesUpdateByIDParams::entity_type,
        ?entity_id: Integer,
        ?note_type: String,
        ?params: top,
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_entity_notes_update_by_id_response

      def events_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_events_get_by_id_response

      def events_list: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_events_list_response

      def events_list_types: (
        ?language_code: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_events_list_types_response

      def leads_create: (
        body: ::Array[Amocrm::APILeadsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_create_response

      def leads_create_complex: (
        body: ::Array[Amocrm::APILeadsCreateComplexParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_create_complex_response

      def leads_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_get_by_id_response

      def leads_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::APILeadsListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_list_response

      def leads_update: (
        body: ::Array[Amocrm::APILeadsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_update_response

      def leads_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::APILeadsUpdateByIDParams::Embedded,
        ?closed_at: Integer,
        ?custom_fields_values: ::Array[Amocrm::APILeadsUpdateByIDParams::CustomFieldsValue],
        ?group_id: Integer,
        ?loss_reason_id: Integer,
        ?name: String,
        ?pipeline_id: Integer,
        ?price: Integer,
        ?responsible_user_id: Integer,
        ?status_id: Integer,
        ?tags_to_add: ::Array[Amocrm::APILeadsUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::APILeadsUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_leads_update_by_id_response

      def pipeline_statuses_create: (
        Integer pipeline_id,
        body: ::Array[Amocrm::APIPipelineStatusesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_create_response

      def pipeline_statuses_delete_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_delete_by_id_response

      def pipeline_statuses_get_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_get_by_id_response

      def pipeline_statuses_list: (
        Integer pipeline_id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_list_response

      def pipeline_statuses_update: (
        Integer pipeline_id,
        body: ::Array[Amocrm::APIPipelineStatusesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_update_response

      def pipeline_statuses_update_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?color: String,
        ?descriptions: ::Array[Amocrm::APIPipelineStatusesUpdateByIDParams::Description],
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipeline_statuses_update_by_id_response

      def pipelines_create: (
        body: ::Array[Amocrm::APIPipelinesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_create_response

      def pipelines_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_delete_by_id_response

      def pipelines_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_get_by_id_response

      def pipelines_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_list_response

      def pipelines_update: (
        body: ::Array[Amocrm::APIPipelinesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_update_response

      def pipelines_update_by_id: (
        Integer id,
        ?is_archive: bool,
        ?is_main: bool,
        ?is_unsorted_on: bool,
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_pipelines_update_by_id_response

      def roles_create: (
        body: ::Array[Amocrm::APIRolesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_roles_create_response

      def roles_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_roles_delete_by_id_response

      def roles_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_roles_get_by_id_response

      def roles_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_roles_list_response

      def roles_update_by_id: (
        Integer id,
        ?name: String,
        ?request_id: String,
        ?rights: Amocrm::APIRolesUpdateByIDParams::Rights?,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_roles_update_by_id_response

      def salesbot_run: (
        body: ::Array[Amocrm::APISalesbotRunParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_salesbot_run_response

      def short_links_create: (
        url: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_short_links_create_response

      def sources_create: (
        body: ::Array[Amocrm::APISourcesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_create_response

      def sources_delete: (
        body: ::Array[Amocrm::APISourcesDeleteParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_delete_response

      def sources_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_delete_by_id_response

      def sources_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_get_by_id_response

      def sources_list: (
        ?filter: Amocrm::APISourcesListParams::Filter,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_list_response

      def sources_update: (
        body: ::Array[Amocrm::APISourcesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_update_response

      def sources_update_by_id: (
        Integer id,
        ?default: bool,
        ?external_id: String,
        ?name: String,
        ?origin_code: String?,
        ?pipeline_id: Integer?,
        ?request_id: String,
        ?services: Amocrm::Models::APISourcesUpdateByIDParams::services,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_sources_update_by_id_response

      def tags_create: (
        Amocrm::Models::APITagsCreateParams::entity_type entity_type,
        body: ::Array[Amocrm::APITagsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tags_create_response

      def tags_list: (
        Amocrm::Models::APITagsListParams::entity_type entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?query: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tags_list_response

      def talks_close: (
        Integer id,
        ?force_close: bool,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_talks_close_response

      def talks_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_talks_get_by_id_response

      def tasks_create: (
        body: ::Array[Amocrm::APITasksCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tasks_create_response

      def tasks_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tasks_get_by_id_response

      def tasks_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::APITasksListParams::query,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tasks_list_response

      def tasks_update: (
        body: ::Array[Amocrm::APITasksUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tasks_update_response

      def tasks_update_by_id: (
        Integer id,
        ?complete_till: Integer,
        ?entity_id: Integer,
        ?entity_type: String,
        ?is_completed: bool,
        ?responsible_user_id: Integer,
        ?result: Amocrm::APITasksUpdateByIDParams::Result,
        ?task_type_id: Integer,
        ?text: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_tasks_update_by_id_response

      def unsorted_leads_accept: (
        String uid,
        ?status_id: Integer,
        ?user_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_unsorted_leads_accept_response

      def unsorted_leads_create_forms: (
        body: ::Array[Amocrm::APIUnsortedLeadsCreateFormsParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_unsorted_leads_create_forms_response

      def unsorted_leads_decline: (
        String uid,
        ?user_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_unsorted_leads_decline_response

      def users_create: (
        body: ::Array[Amocrm::APIUsersCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_users_create_response

      def users_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_users_get_by_id_response

      def users_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_users_list_response

      def webhooks_list: (
        ?filter: Amocrm::APIWebhooksListParams::Filter,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_webhooks_list_response

      def webhooks_subscribe: (
        destination: String,
        settings: ::Array[String],
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_webhooks_subscribe_response

      def webhooks_unsubscribe: (
        destination: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_webhooks_unsubscribe_response

      def website_buttons_connect_online_chat: (
        Integer source_id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_website_buttons_connect_online_chat_response

      def website_buttons_create: (
        pipeline_id: Integer,
        ?is_used_in_app: bool,
        ?trusted_websites: ::Array[String],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_website_buttons_create_response

      def website_buttons_get_by_source_id: (
        Integer source_id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_website_buttons_get_by_source_id_response

      def website_buttons_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_website_buttons_list_response

      def website_buttons_update: (
        Integer source_id,
        trusted_websites: Amocrm::APIWebsiteButtonsUpdateParams::TrustedWebsites,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_website_buttons_update_response

      def widget_bot_continue_continue: (
        Integer continue_id,
        bot_type: Amocrm::Models::APIWidgetBotContinueContinueParams::bot_type,
        bot_id: Integer,
        ?data: top,
        ?execute_handlers: ::Array[Amocrm::APIWidgetBotContinueContinueParams::ExecuteHandler],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_widget_bot_continue_continue_response

      def widgets_get_by_code: (
        String widget_code,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_widgets_get_by_code_response

      def widgets_install: (
        String widget_code,
        body: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_widgets_install_response

      def widgets_list: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_widgets_list_response

      def widgets_uninstall: (
        String widget_code,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::api_widgets_uninstall_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
