module Amocrm
  module Resources
    class Calls
      def create: (
        body: ::Array[Amocrm::CallCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::call_create_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
