module Amocrm
  module Resources
    class CustomerSegments
      def create: (
        body: ::Array[Amocrm::CustomerSegmentCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::customer_segment_create_response

      def list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::customer_segment_list_response

      def delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::customer_segment_delete_by_id_response

      def get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::customer_segment_get_by_id_response

      def update_by_id: (
        Integer id,
        ?color: String,
        ?custom_fields_values: ::Array[Amocrm::CustomerSegmentUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::customer_segment_update_by_id_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
