module Amocrm
  module Resources
    class CustomFieldGroups
      def create: (
        String entity_type,
        body: ::Array[Amocrm::CustomFieldGroupCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::custom_field_group_create_response

      def list: (
        String entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::custom_field_group_list_response

      def delete_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::custom_field_group_delete_by_id_response

      def get_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::custom_field_group_get_by_id_response

      def update_by_id: (
        Integer id,
        entity_type: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::custom_field_group_update_by_id_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
