module Amocrm
  module Resources
    class Pet
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Amocrm::PetAPI::Category,
        ?status: Amocrm::Models::PetAPI::status,
        ?tags: ::Array[Amocrm::PetAPI::Tag],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::PetAPI

      def retrieve: (
        Integer pet_id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::PetAPI

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: Amocrm::PetAPI::Category,
        ?status: Amocrm::Models::PetAPI::status,
        ?tags: ::Array[Amocrm::PetAPI::Tag],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::PetAPI

      def delete: (
        Integer pet_id,
        ?request_options: Amocrm::request_opts
      ) -> nil

      def find_by_status: (
        ?status: Amocrm::Models::PetFindByStatusParams::status,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::pet_find_by_tags_response

      def update_with_form: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: Amocrm::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        body: Amocrm::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::PetUploadImageResponse

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
