module Amocrm
  module Resources
    class Talks
      def close: (
        Integer id,
        ?force_close: bool,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::talk_close_response

      def get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::talk_get_by_id_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
