module Amocrm
  module Resources
    class User
      def create: (
        ?id: Integer,
        ?email: String,
        ?first_name: String,
        ?last_name: String,
        ?password: String,
        ?phone: String,
        ?username: String,
        ?user_status: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::UserAPI

      def retrieve: (
        String username,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::UserAPI

      def update: (
        String existing_username,
        ?id: Integer,
        ?email: String,
        ?first_name: String,
        ?last_name: String,
        ?password: String,
        ?phone: String,
        ?username: String,
        ?user_status: Integer,
        ?request_options: Amocrm::request_opts
      ) -> nil

      def delete: (
        String username,
        ?request_options: Amocrm::request_opts
      ) -> nil

      def create_with_list: (
        ?body: ::Array[Amocrm::UserAPI],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::UserAPI

      def login: (
        ?password: String,
        ?username: String,
        ?request_options: Amocrm::request_opts
      ) -> String

      def logout: (?request_options: Amocrm::request_opts) -> nil

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
