module Amocrm
  module Resources
    class V2
      def salesbot_run: (
        body: ::Array[Amocrm::V2SalesbotRunParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v2_salesbot_run_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
