module Amocrm
  module Resources
    class V4
      def account_get: (
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_account_get_response

      def calls_create: (
        body: ::Array[Amocrm::V4CallsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_calls_create_response

      def catalog_elements_create: (
        Integer catalog_id,
        body: ::Array[Amocrm::V4CatalogElementsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalog_elements_create_response

      def catalog_elements_get_by_id: (
        Integer id,
        catalog_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalog_elements_get_by_id_response

      def catalog_elements_list: (
        Integer catalog_id,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?query: Amocrm::Models::V4CatalogElementsListParams::query,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalog_elements_list_response

      def catalog_elements_update: (
        Integer catalog_id,
        body: ::Array[Amocrm::V4CatalogElementsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalog_elements_update_response

      def catalog_elements_update_by_id: (
        Integer id,
        catalog_id: Integer,
        ?custom_fields_values: ::Array[Amocrm::V4CatalogElementsUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_id: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalog_elements_update_by_id_response

      def catalogs_create: (
        body: ::Array[Amocrm::V4CatalogsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalogs_create_response

      def catalogs_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalogs_get_by_id_response

      def catalogs_list: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalogs_list_response

      def catalogs_update: (
        body: ::Array[Amocrm::V4CatalogsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalogs_update_response

      def catalogs_update_by_id: (
        Integer id,
        ?can_add_elements: bool,
        ?can_link_multiple: bool,
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_catalogs_update_by_id_response

      def companies_create: (
        body: ::Array[Amocrm::V4CompaniesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_companies_create_response

      def companies_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_companies_get_by_id_response

      def companies_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::V4CompaniesListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_companies_list_response

      def companies_update: (
        body: ::Array[Amocrm::V4CompaniesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_companies_update_response

      def companies_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::V4CompaniesUpdateByIDParams::Embedded,
        ?created_at: Integer,
        ?created_by: Integer,
        ?custom_fields_values: ::Array[Amocrm::V4CompaniesUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?responsible_user_id: Integer,
        ?tags_to_add: ::Array[Amocrm::V4CompaniesUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::V4CompaniesUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_companies_update_by_id_response

      def contact_chats_link: (
        body: ::Array[Amocrm::V4ContactChatsLinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contact_chats_link_response

      def contact_chats_list: (
        ?filter: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contact_chats_list_response

      def contacts_create: (
        body: ::Array[Amocrm::V4ContactsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contacts_create_response

      def contacts_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contacts_get_by_id_response

      def contacts_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::V4ContactsListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contacts_list_response

      def contacts_update: (
        body: ::Array[Amocrm::V4ContactsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contacts_update_response

      def contacts_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::V4ContactsUpdateByIDParams::Embedded,
        ?created_at: Integer,
        ?created_by: Integer,
        ?custom_fields_values: ::Array[Amocrm::V4ContactsUpdateByIDParams::CustomFieldsValue],
        ?first_name: String,
        ?last_name: String,
        ?name: String,
        ?responsible_user_id: Integer,
        ?tags_to_add: ::Array[Amocrm::V4ContactsUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::V4ContactsUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_contacts_update_by_id_response

      def custom_field_groups_create: (
        String entity_type,
        body: ::Array[Amocrm::V4CustomFieldGroupsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_field_groups_create_response

      def custom_field_groups_delete_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_field_groups_delete_by_id_response

      def custom_field_groups_get_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_field_groups_get_by_id_response

      def custom_field_groups_list: (
        String entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_field_groups_list_response

      def custom_field_groups_update_by_id: (
        Integer id,
        entity_type: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_field_groups_update_by_id_response

      def custom_fields_create: (
        String entity_type,
        body: ::Array[Amocrm::V4CustomFieldsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_create_response

      def custom_fields_delete_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_delete_by_id_response

      def custom_fields_get_by_id: (
        Integer id,
        entity_type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_get_by_id_response

      def custom_fields_list: (
        String entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_list_response

      def custom_fields_update: (
        String entity_type,
        body: ::Array[Amocrm::V4CustomFieldsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_update_response

      def custom_fields_update_by_id: (
        Integer id,
        entity_type: String,
        ?code: String,
        ?enums: ::Array[top],
        ?group_id: Integer,
        ?is_deletable: bool,
        ?is_multiple: bool,
        ?is_required: bool,
        ?is_visible: bool,
        ?name: String,
        ?settings: top,
        ?sort: Integer,
        ?type: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_custom_fields_update_by_id_response

      def customer_bonus_points_change: (
        Integer customer_id,
        earn: Integer,
        redeem: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_bonus_points_change_response

      def customer_segments_create: (
        body: ::Array[Amocrm::V4CustomerSegmentsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_segments_create_response

      def customer_segments_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_segments_delete_by_id_response

      def customer_segments_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_segments_get_by_id_response

      def customer_segments_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_segments_list_response

      def customer_segments_update_by_id: (
        Integer id,
        ?color: String,
        ?custom_fields_values: ::Array[Amocrm::V4CustomerSegmentsUpdateByIDParams::CustomFieldsValue],
        ?name: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_segments_update_by_id_response

      def customer_statuses_create: (
        body: ::Array[Amocrm::V4CustomerStatusesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_statuses_create_response

      def customer_statuses_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_statuses_delete_by_id_response

      def customer_statuses_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_statuses_get_by_id_response

      def customer_statuses_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_statuses_list_response

      def customer_statuses_update_by_id: (
        Integer id,
        ?color: String,
        ?name: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_statuses_update_by_id_response

      def customer_transactions_create: (
        Integer customer_id,
        body: ::Array[Amocrm::V4CustomerTransactionsCreateParams::Body],
        ?accrue_bonus: bool,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_transactions_create_response

      def customer_transactions_delete_by_id: (
        Integer transaction_id,
        customer_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_transactions_delete_by_id_response

      def customer_transactions_list: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_transactions_list_response

      def customer_transactions_list_by_customer: (
        Integer customer_id,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customer_transactions_list_by_customer_response

      def customers_create: (
        body: ::Array[Amocrm::V4CustomersCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_create_response

      def customers_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_get_by_id_response

      def customers_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::V4CustomersListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_list_response

      def customers_mode_set_mode: (
        is_enabled: bool,
        mode: Amocrm::Models::V4CustomersModeSetModeParams::mode,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_mode_set_mode_response

      def customers_update: (
        body: ::Array[Amocrm::V4CustomersUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_update_response

      def customers_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::V4CustomersUpdateByIDParams::Embedded,
        ?custom_fields_values: ::Array[Amocrm::V4CustomersUpdateByIDParams::CustomFieldsValue],
        ?main_user_id: Integer,
        ?name: String,
        ?next_date: Integer,
        ?next_price: Integer,
        ?periodicity: Integer,
        ?responsible_user_id: Integer,
        ?status_id: Integer,
        ?tags_to_add: ::Array[Amocrm::V4CustomersUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::V4CustomersUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_customers_update_by_id_response

      def entity_followers_add: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityFollowersAddParams::entity_type,
        body: ::Array[Amocrm::V4EntityFollowersAddParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_followers_add_response

      def entity_followers_list: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityFollowersListParams::entity_type,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_followers_list_response

      def entity_followers_remove: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityFollowersRemoveParams::entity_type,
        body: ::Array[Amocrm::V4EntityFollowersRemoveParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_followers_remove_response

      def entity_links_link: (
        Amocrm::Models::V4EntityLinksLinkParams::entity_type entity_type,
        body: ::Array[Amocrm::V4EntityLinksLinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_link_response

      def entity_links_link_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityLinksLinkByEntityParams::entity_type,
        body: ::Array[Amocrm::V4EntityLinksLinkByEntityParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_link_by_entity_response

      def entity_links_list: (
        Amocrm::Models::V4EntityLinksListParams::entity_type entity_type,
        ?filter: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_list_response

      def entity_links_list_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityLinksListByEntityParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_list_by_entity_response

      def entity_links_unlink: (
        Amocrm::Models::V4EntityLinksUnlinkParams::entity_type entity_type,
        body: ::Array[Amocrm::V4EntityLinksUnlinkParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_unlink_response

      def entity_links_unlink_by_entity: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityLinksUnlinkByEntityParams::entity_type,
        body: ::Array[Amocrm::V4EntityLinksUnlinkByEntityParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_links_unlink_by_entity_response

      def entity_notes_by_parent_create_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityNotesByParentCreateByParentParams::entity_type,
        body: ::Array[Amocrm::V4EntityNotesByParentCreateByParentParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_by_parent_create_by_parent_response

      def entity_notes_by_parent_get_by_parent_id: (
        Integer note_id,
        entity_type: Amocrm::Models::V4EntityNotesByParentGetByParentIDParams::entity_type,
        entity_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_by_parent_get_by_parent_id_response

      def entity_notes_by_parent_list_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityNotesByParentListByParentParams::entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_by_parent_list_by_parent_response

      def entity_notes_by_parent_update_by_parent: (
        Integer entity_id,
        entity_type: Amocrm::Models::V4EntityNotesByParentUpdateByParentParams::entity_type,
        body: ::Array[Amocrm::V4EntityNotesByParentUpdateByParentParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_by_parent_update_by_parent_response

      def entity_notes_by_parent_update_by_parent_id: (
        Integer note_id,
        entity_type: Amocrm::Models::V4EntityNotesByParentUpdateByParentIDParams::entity_type,
        ?body_entity_id: Integer,
        ?note_type: String,
        ?params: top,
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_by_parent_update_by_parent_id_response

      def entity_notes_create: (
        Amocrm::Models::V4EntityNotesCreateParams::entity_type entity_type,
        body: ::Array[Amocrm::V4EntityNotesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_create_response

      def entity_notes_get_by_id: (
        Integer id,
        entity_type: Amocrm::Models::V4EntityNotesGetByIDParams::entity_type,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_get_by_id_response

      def entity_notes_list: (
        Amocrm::Models::V4EntityNotesListParams::entity_type entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_list_response

      def entity_notes_pin: (
        Integer id,
        entity_type: Amocrm::Models::V4EntityNotesPinParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_pin_response

      def entity_notes_unpin: (
        Integer id,
        entity_type: Amocrm::Models::V4EntityNotesUnpinParams::entity_type,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_unpin_response

      def entity_notes_update: (
        Amocrm::Models::V4EntityNotesUpdateParams::entity_type entity_type,
        body: ::Array[Amocrm::V4EntityNotesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_update_response

      def entity_notes_update_by_id: (
        Integer id,
        entity_type: Amocrm::Models::V4EntityNotesUpdateByIDParams::entity_type,
        ?entity_id: Integer,
        ?note_type: String,
        ?params: top,
        ?updated_at: Integer,
        ?updated_by: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_entity_notes_update_by_id_response

      def events_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_events_get_by_id_response

      def events_list: (
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_events_list_response

      def events_list_types: (
        ?language_code: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_events_list_types_response

      def leads_create: (
        body: ::Array[Amocrm::V4LeadsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_create_response

      def leads_create_complex: (
        body: ::Array[Amocrm::V4LeadsCreateComplexParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_create_complex_response

      def leads_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_get_by_id_response

      def leads_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::V4LeadsListParams::query,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_list_response

      def leads_update: (
        body: ::Array[Amocrm::V4LeadsUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_update_response

      def leads_update_by_id: (
        Integer id,
        ?_embedded: Amocrm::V4LeadsUpdateByIDParams::Embedded,
        ?closed_at: Integer,
        ?custom_fields_values: ::Array[Amocrm::V4LeadsUpdateByIDParams::CustomFieldsValue],
        ?group_id: Integer,
        ?loss_reason_id: Integer,
        ?name: String,
        ?pipeline_id: Integer,
        ?price: Integer,
        ?responsible_user_id: Integer,
        ?status_id: Integer,
        ?tags_to_add: ::Array[Amocrm::V4LeadsUpdateByIDParams::TagsToAdd],
        ?tags_to_delete: ::Array[Amocrm::V4LeadsUpdateByIDParams::TagsToDelete],
        ?updated_at: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_leads_update_by_id_response

      def pipeline_statuses_create: (
        Integer pipeline_id,
        body: ::Array[Amocrm::V4PipelineStatusesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_create_response

      def pipeline_statuses_delete_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_delete_by_id_response

      def pipeline_statuses_get_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_get_by_id_response

      def pipeline_statuses_list: (
        Integer pipeline_id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_list_response

      def pipeline_statuses_update: (
        Integer pipeline_id,
        body: ::Array[Amocrm::V4PipelineStatusesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_update_response

      def pipeline_statuses_update_by_id: (
        Integer id,
        pipeline_id: Integer,
        ?color: String,
        ?descriptions: ::Array[Amocrm::V4PipelineStatusesUpdateByIDParams::Description],
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipeline_statuses_update_by_id_response

      def pipelines_create: (
        body: ::Array[Amocrm::V4PipelinesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_create_response

      def pipelines_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_delete_by_id_response

      def pipelines_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_get_by_id_response

      def pipelines_list: (
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_list_response

      def pipelines_update: (
        body: ::Array[Amocrm::V4PipelinesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_update_response

      def pipelines_update_by_id: (
        Integer id,
        ?is_archive: bool,
        ?is_main: bool,
        ?is_unsorted_on: bool,
        ?name: String,
        ?request_id: String,
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_pipelines_update_by_id_response

      def roles_create: (
        body: ::Array[Amocrm::V4RolesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_roles_create_response

      def roles_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_roles_delete_by_id_response

      def roles_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_roles_get_by_id_response

      def roles_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_roles_list_response

      def roles_update_by_id: (
        Integer id,
        ?name: String,
        ?request_id: String,
        ?rights: Amocrm::V4RolesUpdateByIDParams::Rights?,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_roles_update_by_id_response

      def short_links_create: (
        url: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_short_links_create_response

      def sources_create: (
        body: ::Array[Amocrm::V4SourcesCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_create_response

      def sources_delete: (
        body: ::Array[Amocrm::V4SourcesDeleteParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_delete_response

      def sources_delete_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_delete_by_id_response

      def sources_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_get_by_id_response

      def sources_list: (
        ?filter: Amocrm::V4SourcesListParams::Filter,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_list_response

      def sources_update: (
        body: ::Array[Amocrm::V4SourcesUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_update_response

      def sources_update_by_id: (
        Integer id,
        ?default: bool,
        ?external_id: String,
        ?name: String,
        ?origin_code: String?,
        ?pipeline_id: Integer?,
        ?request_id: String,
        ?services: Amocrm::Models::V4SourcesUpdateByIDParams::services,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_sources_update_by_id_response

      def tags_create: (
        Amocrm::Models::V4TagsCreateParams::entity_type entity_type,
        body: ::Array[Amocrm::V4TagsCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tags_create_response

      def tags_list: (
        Amocrm::Models::V4TagsListParams::entity_type entity_type,
        ?filter: top,
        ?limit: Integer,
        ?page: Integer,
        ?query: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tags_list_response

      def talks_close: (
        Integer id,
        ?force_close: bool,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_talks_close_response

      def talks_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_talks_get_by_id_response

      def tasks_create: (
        body: ::Array[Amocrm::V4TasksCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tasks_create_response

      def tasks_get_by_id: (
        Integer id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tasks_get_by_id_response

      def tasks_list: (
        ?filter: top,
        ?limit: Integer,
        ?order: top,
        ?page: Integer,
        ?query: Amocrm::Models::V4TasksListParams::query,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tasks_list_response

      def tasks_update: (
        body: ::Array[Amocrm::V4TasksUpdateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tasks_update_response

      def tasks_update_by_id: (
        Integer id,
        ?complete_till: Integer,
        ?entity_id: Integer,
        ?entity_type: String,
        ?is_completed: bool,
        ?responsible_user_id: Integer,
        ?result: Amocrm::V4TasksUpdateByIDParams::Result,
        ?task_type_id: Integer,
        ?text: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_tasks_update_by_id_response

      def unsorted_leads_accept: (
        String uid,
        ?status_id: Integer,
        ?user_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_unsorted_leads_accept_response

      def unsorted_leads_create_forms: (
        body: ::Array[Amocrm::V4UnsortedLeadsCreateFormsParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_unsorted_leads_create_forms_response

      def unsorted_leads_decline: (
        String uid,
        ?user_id: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_unsorted_leads_decline_response

      def users_create: (
        body: ::Array[Amocrm::V4UsersCreateParams::Body],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_users_create_response

      def users_get_by_id: (
        Integer id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_users_get_by_id_response

      def users_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_users_list_response

      def webhooks_list: (
        ?filter: Amocrm::V4WebhooksListParams::Filter,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_webhooks_list_response

      def webhooks_subscribe: (
        destination: String,
        settings: ::Array[String],
        ?sort: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_webhooks_subscribe_response

      def webhooks_unsubscribe: (
        destination: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_webhooks_unsubscribe_response

      def website_buttons_connect_online_chat: (
        Integer source_id,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_website_buttons_connect_online_chat_response

      def website_buttons_create: (
        pipeline_id: Integer,
        ?is_used_in_app: bool,
        ?trusted_websites: ::Array[String],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_website_buttons_create_response

      def website_buttons_get_by_source_id: (
        Integer source_id,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_website_buttons_get_by_source_id_response

      def website_buttons_list: (
        ?limit: Integer,
        ?page: Integer,
        ?with: String,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_website_buttons_list_response

      def website_buttons_update: (
        Integer source_id,
        trusted_websites: Amocrm::V4WebsiteButtonsUpdateParams::TrustedWebsites,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_website_buttons_update_response

      def widget_bot_continue_continue: (
        Integer continue_id,
        bot_type: Amocrm::Models::V4WidgetBotContinueContinueParams::bot_type,
        bot_id: Integer,
        ?data: top,
        ?execute_handlers: ::Array[Amocrm::V4WidgetBotContinueContinueParams::ExecuteHandler],
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_widget_bot_continue_continue_response

      def widgets_get_by_code: (
        String widget_code,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_widgets_get_by_code_response

      def widgets_install: (
        String widget_code,
        body: top,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_widgets_install_response

      def widgets_list: (
        ?limit: Integer,
        ?page: Integer,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_widgets_list_response

      def widgets_uninstall: (
        String widget_code,
        ?request_options: Amocrm::request_opts
      ) -> Amocrm::Models::v4_widgets_uninstall_response

      def initialize: (client: Amocrm::Client) -> void
    end
  end
end
